Major refactor: mostly optimizations.

diff --git a/usr/local/bin/btd-time-temp b/usr/local/bin/btd-time-temp
--- a/usr/local/bin/btd-time-temp
+++ b/usr/local/bin/btd-time-temp
@@ -6,7 +6,7 @@
 
 # This script complies with Semantic Versioning: http://semver.org/
 vMajor=0
-vMinor=1
+vMinor=2
 vPatch=1
 vHash='$Hash$'
 
@@ -61,44 +61,22 @@ vHash='$Hash$'
 ## Hosts->[hostname]->Dropboxes. The dropbox folder must match the
 ## shell parameter RD_DROPBOX_DIR in this script (see below).
 ##
-## FFMPEG. The script uses the ffmpeg command to concatenate the time
-## audio file and the temperature audio file into a single audio
+## zsh(1): needed to run this script. Install it with `sudo yum
+## install zsh`.
+##
+## xmlstarlet(1): this is used to parse the XML from the NWS
+## website. Install it with the command `sudo yum install xmlstarlet`
+## (from the epel repository).
+##
+## ffmpeg(1): The script uses the ffmpeg command to concatenate the
+## time audio file and the temperature audio file into a single
 ## file. It then places that single audio file in the Rivendell
-## dropbox folder.
+## dropbox folder. Install it with the command `sudo yum install
+## ffmpeg` (from the nux-dextop repository).
 ##
 ##############################################################################
 ##############################################################################
-
-##############################################################################
-##############################################################################
 ##
-## CONFIGURATION
-##
-## This secton of the file contains configuration settings for this script.
-## Defaults may be overridden by setting shell environment variables by
-## the thing what calls this script.
-##
-##############################################################################
-##############################################################################
-TOP_DIR="${TOP_DIR:-/usr/local/share/time-temp}"
-TEMPERATURE_DIR="${TEMPERATURE_DIR:-${TOP_DIR}/TempAnnounce}"
-TIME_DIR="${TIME_DIR:-${TOP_DIR}/TimeAnnounce}"
-
-## The value of this parameter must match the Rivendell dropbox
-## configuration. Try to look it up in the database, and default to
-## /var/tmp/time-temp if not found.
-RD_DROPBOX_DIR=$(doSQL "select PATH from DROPBOXES where PATH like '%time%temp%'")
-## Strip off the trailing wildcard character(s).
-RD_DROPBOX_DIR=${RD_DROPBOX_DIR%/*}
-
-## United States National Weather Service current observation URL
-## base.
-NWS_XML_URL_BASE="https://w1.weather.gov/xml/current_obs"
-
-## Default temperature unit is Farenheit. Specify Celcius in the
-## calling environment variable TEMPERATURE_UNIT (case is ignored).
-TEMPERATURE_UNIT=${TEMPERATURE_UNIT:-f}
-
 ##############################################################################
 ##############################################################################
 ##
@@ -117,18 +95,27 @@ file containing same into the Rivendell Library.
 
 SUMMARY
 
-${my_name} --location (-l) <NWS Location Code>
+${my_name} [ --verbose ... ]
+              --cart (-c) <Cart Number> --location (-l) <NWS Location Code>
 
 DESCRIPTION
 
 ${my_name} captures the current time of day and the current reported
 temperature from the US National Weather Service into a single audio
-file and imports that audio file to a specified Cart in the Rivendell
-Library.
+file and uses rdimport(1) to import that audio file to a specified
+Cart in the Rivendell Library.
 
-The sole command line argument is mandatory. Use it to specify the NWS
-location code for which to retrieve the current temperature (see
-https://w1.weather.gov/xml/current_obs/seek.php?Find=Find).
+The command line arguments --cart and --location are mandatory. Use
+--cart (short option: -c) to specify the Rivendell Cart Number. Use
+--location (short option -l) to specify the NWS location code for
+which to retrieve the current temperature from the US National Weather
+Service (see https://w1.weather.gov/xml/current_obs/seek.php?Find=Find
+for all available locations).
+
+Use the command line parameter --verbose to make ${my_name} more
+chatty about its progress. Use one -v to output status. Use two or
+more -v to run the script with "xtrace" turned on (see man zshoptions
+for explanation and details of the xtrace option).
 
 EOF
 }
@@ -270,10 +257,10 @@ zmodload zsh/datetime
 zmodload zsh/stat
 
 ############# BEGIN external shell commands used in this script. #############
-# This script uses these 15 external commands.
+# This script uses these 13 external commands.
 # Look for them in their upper case, parameter expanded form.
 typeset -a our_commands
-our_commands=( awk cat chmod chown ffmpeg grep logger mktemp mv mysql rm sed sudo wget xmlstarlet )
+our_commands=( awk cat ffmpeg grep logger mktemp mv mysql rdimport rm sed wget xmlstarlet )
 # Find the executables we need; this uses some basic shell and a ZSH trick:
 # the (U) in the eval says to evaluate the parameter as all upper case
 # letters. This snippet generates shell parameters representing the upper case
@@ -291,10 +278,52 @@ done
 unset our_commands
 ############## END external shell commands used in this script. ##############
 
-typeset -i VERBOSE=0
-NWS_LOCATION_CODE=''
+## Log STDOUT and STDERR of this script and all commands called by this
+## script to separate files.
+exec 1> "/var/tmp/${0##*/}.out"
+exec 2> "/var/tmp/${0##*/}.err"
 
-if ! TEMP=$(getopt -o l:hVv --long location:,help,version,verbose -n "${0##*/}" -- "${@}") ; then
+typeset -i VERBOSE=0
+LOGGER_VERBOSE=''
+
+##############################################################################
+##############################################################################
+##
+## CONFIGURATION
+##
+## This secton of the file contains configuration settings for this script.
+## Defaults may be overridden by setting shell environment variables by
+## the thing what calls this script.
+##
+##############################################################################
+##############################################################################
+NWS_LOCATION_CODE=''
+typeset -i TO_CART=0
+
+TOP_DIR="${TOP_DIR:-/usr/local/share/time-temp}"
+TEMPERATURE_DIR="${TEMPERATURE_DIR:-${TOP_DIR}/TempAnnounce}"
+TIME_DIR="${TIME_DIR:-${TOP_DIR}/TimeAnnounce}"
+
+## The value of this parameter must match the Rivendell dropbox
+## configuration. Try to look it up in the database, and default to
+## /var/tmp/time-temp if not found.
+RD_DROPBOX_DIR=$(doSQL "select PATH from DROPBOXES where PATH like '%time%temp%'")
+## Strip off the trailing wildcard character(s).
+RD_DROPBOX_DIR=${RD_DROPBOX_DIR%/*}
+
+## United States National Weather Service current observation URL
+## base.
+NWS_XML_URL_BASE="https://w1.weather.gov/xml/current_obs"
+
+## Default temperature unit is Farenheit. Specify Celcius in the
+## calling environment variable TEMPERATURE_UNIT (case is ignored).
+TEMPERATURE_UNIT=${TEMPERATURE_UNIT:-f}
+
+## We poll the NWS only once per hour since they update the conditions
+## only that often. Use the file in $(LAST_OBSERVATION} as a cache.
+typeset -r LAST_OBSERVATION="${TOP_DIR}/last-observation"
+
+if ! TEMP=$(getopt -o c:l:hVv --long cart:,location:,help,version,verbose -n "${0##*/}" -- "${@}") ; then
   echo "getopt(1) Fatal Error (${?}). Terminating..." >&2
   return 1
 fi
@@ -303,6 +332,7 @@ while : ; do
   # VERBOSE is used, but in a non-Bash way.
   # shellcheck disable=SC2034
   case "${1}" in
+    -c|--cart) TO_CART="${2}" ; shift 2 ;;
     -l|--location) NWS_LOCATION_CODE="${2}" ; shift 2 ;;
     -h|--help*) usage "${0}" ; exit ;;
     -v|--verb*) ((VERBOSE += 1)) ; shift ;;
@@ -316,29 +346,57 @@ if ((showVersion)) ; then
   echo "${0##*/}: version ${vMajor}.${vMinor}.${vPatch}-${${vHash#\$Hash: }%$}"
   exit 0
 fi
-## Make sure they specified all three required parameters.
+
+## Enable script tracing and logger(1) output to STDERR for
+## troubleshooting if they specified --verbose mode on the command
+## line.
+((VERBOSE)) && typeset -r LOGGER_VERBOSE="--stderr"
+if ((VERBOSE > 1)) ; then
+  setopt xtrace
+fi
+
+## Make sure they specified both of the required parameters.
+if [[ -z "${TO_CART}" ]] ; then
+  ${LOGGER} "${LOGGER_VERBOSE}" "${0:t}" -p local7.error -i "ERROR: Missing Rivendell cart number on the command line."
+  usage "${0}"
+  exit 2
+fi
 if [[ -z "${NWS_LOCATION_CODE}" ]] ; then
-  ${LOGGER} --stderr -t "${0:t}" -p local7.error -i "ERROR: Missing NWS Location Code."
+  ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.error -i "ERROR: Missing NWS Location Code on the command line."
   usage "${0}"
   exit 3
 fi
 
+## Make sure the data directory is writable by the user running this
+## script.
+if ! [[ -w "${TOP_DIR}" ]] ; then
+  ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.error -i "ERROR: Missing write permission on the cache directory '${TOP_DIR}'. Please adjust permissions."
+  exit 1
+fi
+  
+
 ## Ask Rivendell what its system-wide sample rate is. Set it to 44100
 ## if we are unable to discern the Rivendell setting.
 if ! okDatabaseStructure SYSTEM:sample_rate ; then
-  ${LOGGER} --stderr -t "${0:t}" -p local7.error -i "ERROR: Incompatible Rivendell database. Missing column 'Rivendell.SYSTEM.SAMPLE_RATE'."
-  exit
+  ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.error -i "ERROR: Incompatible Rivendell database. Missing column 'Rivendell.SYSTEM.SAMPLE_RATE'."
+  exit 4
 fi
 sample_rate=$(doSQL "select SAMPLE_RATE from SYSTEM")
 typeset -r sample_rate=${sample_rate:-44100}
+((VERBOSE)) && ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.notice -i "NOTICE: Using system sample rate '${sample_rate}' for audio transcoding."
 
-## Ask Rivendell for the number of the Time and Temperature Cart.  How
-## will this fail when there are either a) zero, or b) multiple time
-## and temperature Carts in the Library?
-if ! okDatabaseStructure CART:title ; then
-  ${LOGGER} --stderr -t "${0:t}" -p local7.error -i "ERROR: Incompatible Rivendell database. Missing column 'Rivendell.CART.TITLE'."
-  exit
+## Obtain the Rivendell Group for for the Cart. rdimport(1) requires
+## this.
+if ! okDatabaseStructure CART:number+group_name ; then
+  ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.error -i "ERROR: Incompatible Rivendell database. Missing columns 'Rivendell.CART.NUMBER' and/or 'Rivendell.CART.GROUP_NAME'."
+  exit 4
 fi
+typeset -r group_name=$(doSQL "select GROUP_NAME from CART where NUMBER=${TO_CART}")
+if [[ -z "${group_name}" ]] ; then
+  ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.error -i "ERROR: Unable to look up Rivendell Group name for Cart '${TO_CART}'."
+  exit 5
+fi
+((VERBOSE)) && ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.notice -i "NOTICE: Importing audio to Cart '${TO_CART}' in Group '${group_name}'."
 
 ## The complete NWS URL is constructed by simply tacking it onto the
 ## end of the base and adding the extension.
@@ -352,23 +410,42 @@ NWS_XML_URL="${NWS_XML_URL_BASE}/${NWS_LOCATION_CODE}.xml"
 ## containing the list of audio files to concatenate with ffmpeg.
 typeset -r current_time="${EPOCHSECONDS}"
 typeset -r hour_minute=$(strftime "%I%M" "${current_time}")
+typeset -r current_minute=$(strftime "%M" "${current_time}")
 
-if ! current_temperature=$(${WGET} --quiet -O - "${NWS_XML_URL}" |
-			     ${XMLSTARLET} c14n --without-comments - |
-			     ${AWK} -F '[<>]' "/temp_${TEMPERATURE_UNIT}/{print \$3}") ; then
-  ${LOGGER} --stderr -t "${0:t}" -p local7.error -i "ERROR:  ${WGET} failed to retrieve data for location '${NWS_LOCATION_CODE}'."
+## Refresh the conditions from the NWS only once per hour.
+## Save this output and use it for all the other minutes in the hour.
+if ((current_minute == 15)) || ! [[ -s "${LAST_OBSERVATION}" ]] ; then
+  ((VERBOSE == 1)) && ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.notice -i "NOTICE: Getting data from NWS for location '${NWS_LOCATION_CODE}'."
+  ## Grab the entire output from the NWS for this location.
+  if ! ${WGET} --quiet -O - "${NWS_XML_URL}" |
+      ${XMLSTARLET} c14n --without-comments - > "${LAST_OBSERVATION}" ; then
+    ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.error -i "ERROR: ${WGET} failed to retrieve data for location '${NWS_LOCATION_CODE}'."
+    exit 1
+  fi
+fi
+## Read the data from the most recent poll, then set the variable to
+## read-only.
+current_observation=$(< "${LAST_OBSERVATION}")
+typeset -r current_observation
+
+## Extract the current temperature (in our unit of choice), the
+## current "weather", and the current wind string from the XML.
+if ! current_temperature=$(echo "${current_observation}" |
+			     ${XMLSTARLET} select -t -v "current_observation/temp_${TEMPERATURE_UNIT}") ; then
+  ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.error -i "ERROR: Unable to extract 'temp_${TEMPERATURE_UNIT}' from '${current_observation}'."
   exit 1
 fi
-if [[ -z "${current_temperature}" ]] ; then
-  ${LOGGER} --stderr -t "${0:t}" -p local7.error -i "ERROR: Unable to retrieve current location '${NWS_LOCATION_CODE}'."
-  exit 2
-fi
-
+current_weather=$(echo "${current_observation}" |
+		    ${XMLSTARLET} select -t -v 'current_observation/weather')
+current_wind_string=$(echo "${current_observation}" |
+			${XMLSTARLET} select -t -v 'current_observation/wind_string')
 ## Drop the fraction to the right of the decimal point in the
 ## retrieved temperature.
 typeset -r current_temperature="${current_temperature%.*}"
+current_conditions="${current_temperature}. ${current_weather}. Wind ${current_wind_string}"
+((VERBOSE)) && ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.notice -i "NOTICE: Currently: '${current_conditions}'"
 
-## Save the concatenated audio in this file.
+## Save the concatenated time and temperature audio in this file.
 typeset -r current_time_and_temperature="$(${MKTEMP} --suffix=.wav)"
 
 ## Set the shell to remove the temporary files on script exit or
@@ -381,26 +458,33 @@ trap "${RM} -f ${current_time_and_temperature}" 0 1 2 3
 ## Use ffmpeg to concatenate and transcode the time and temperature
 ## audio files into a PCM file with the sample rate that matches the
 ## system setting in Rivendell.
+((VERBOSE)) && ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.notice -i "NOTICE: ffmpeg: 'concat:${TIME_DIR}/${hour_minute}|${TEMPERATURE_DIR}/${current_temperature}'"
 ${FFMPEG} -y -loglevel quiet -i "concat:${TIME_DIR}/${hour_minute}|${TEMPERATURE_DIR}/${current_temperature}" -c pcm_s16le -ar "${sample_rate}" "${current_time_and_temperature}"
 
 if ! [[ -s "${current_time_and_temperature}" ]] ; then
-  ${LOGGER} --stderr -t "${0:t}" -p local7.error -i "ERROR: created an empty audio file that was supposed to have the time and temperature."
+  ${LOGGER} "${LOGGER_VERBOSE}" -t "${0:t}" -p local7.error -i "ERROR: created an empty audio file that was supposed to have the time and temperature."
   exit 4
 fi
 
-## Move the generated file into the Rivendell dropbox folder.
-if [[ -z "${RD_DROPBOX_DIR}" ]] ; then
-  ${LOGGER} --stderr -t "${0:t}" -p local7.notice -i "NOTICE: Unable to find a Rivendell dropbox for Time and Temperature."
-  exit 6
+## Use rdimport(1) to import the audio to the specified Cart.
+delete_source='--delete-source'
+if ((VERBOSE)) ; then
+  typeset -r delete_source=''
 fi
-if ! [[ -d "${RD_DROPBOX_DIR}" ]] ; then
-  ${LOGGER} --stderr -t "${0:t}" -p local7.error -i "ERROR: Missing Rivendell dropbox folder ${RD_DROPBOX_DIR}."
-  exit 7
-fi
-if ! ${MV} "${current_time_and_temperature}" "${RD_DROPBOX_DIR}" ; then
-  ${LOGGER} --stderr -t "${0:t}" -p local7.error -i "ERROR: Unable to move audio file to '${RD_DROPBOX_DIR}' (${?})."
-  exit 8
-fi
+## We need to leave variables used as command line parameters unquoted
+## otherwise rdimport(1) interprets them as required parameters.
+# shellcheck disable=SC2248
+${RDIMPORT} \
+  ${VERBOSE:+'--verbose'} \
+  --autotrim-level=-40 \
+  --delete-cuts \
+  ${delete_source} \
+  --fix-broken-formats \
+  --set-string-artist="Current Conditions" \
+  --set-string-title="${current_conditions}" \
+  --to-cart="${TO_CART}" \
+  "${group_name}" \
+  "${current_time_and_temperature}"
 
 exit
 
