Add version info; Do not overwrite existing Logs unless --force; Add usage(); Allow specification of 'day-spec' on command line; Check for Desktop folder; Add robustness.

diff --git a/usr/local/bin/btd-log-generate b/usr/local/bin/btd-log-generate
--- a/usr/local/bin/btd-log-generate
+++ b/usr/local/bin/btd-log-generate
@@ -3,7 +3,7 @@
 ##############################################################################
 ##############################################################################
 ##
-## Generate logs for the main service (e.g., Production)
+## Generate logs for all Rivendell services.
 ##
 ## See also: rdlogmanager --help
 ##
@@ -12,11 +12,42 @@
 
 zmodload zsh/datetime
 
+# This script complies with Semantic Versioning: http://semver.org/
+vMajor=0
+vMinor=1
+vPatch=2
+vHash='$Hash$'
+
+# Do not overwrite existing log by default (see options below).
+unset FORCE
+
+usage() {
+  local myName=${1:t}
+
+  cat <<EOF
+${myName} [ --force (-f) ] [ --when (-w) <day-spec> ]
+                 [ --help (-h) ] [ --version (-v) ]
+
+$(${FMT} <<<"${myName} uses rdlogmanager(1) to generate logs for all SERVICES for 'tomorrow' (the day after the current day). On Fridays it also generates logs for all SERVICES for Sunday and Monday.")
+
+$(${FMT} <<<"By default, ${myName} does not overwrite existing logs. You may force overwriting existing logs by calling ${myName} with the '--force' ('-f') option.")
+
+$(${FMT} <<<"You may specify the day for which rdlogmanager(1) generates the log by calling ${myName} with the '--when' option. See 'rdlogmanager --help' for details about this option.")
+
+$(${FMT} <<<"${myName} saves the output of rdlogmanager(1) in the Desktop folder of the calling user, and also emails the output to the addresses listed in the MAILTO shell variable.")
+
+$(${FMT} <<<"See rdlogmanager --help for additional details.")
+
+EOF
+}
+
 #################  BEGIN shell commands used in this script.  #################
-# This script uses these 5 external commands.
+# This script uses these 7 external commands.
 # Look for them in their upper case, parameter expanded form.
 ourCommands=(
   cp
+  fmt
+  getopt
   logger
   mktemp
   rdlogmanager
@@ -34,13 +65,35 @@ for C in ${ourCommands} ; do
 done
 ##################  END shell commands used in this script.  ##################
 
+## Use getopt to parse the command line arguments.
+TEMP=$(${GETOPT} -o fhvw: --long force,help,version,when: -n ${0:t} -- "${@}")
+if [ ${?} != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+## Note the quotes around "$TEMP": they are essential!
+eval set -- "${TEMP}"
+while :
+do
+  case "${1}" in
+    -f|--forc) FORCE=1 ; shift ;;
+    -h|--help) usage ${0} ; exit ;;
+    -v|--ver*) showVersion=1 ; shift ;;
+    -w|--when) WHEN=${2} ; shift 2 ;;
+    --) shift ; break ;;
+    *) echo 'Internal error!' ; exit 1 ;;
+  esac
+done
+unset TEMP
+
+if ((showVersion)) ; then
+  echo "${0##*/}: version ${vMajor}.${vMinor}.${vPatch}-${${vHash#\$Hash: }%$}"
+  exit 0
+fi
+
 if [[ -r /usr/local/bin/zsh-functions ]] ; then
     source /usr/local/bin/zsh-functions
 else
     ${LOGGER} --stderr -t ${0##*/} -p local7.err -i "ERROR: Cannot continue without /usr/local/bin/zsh-functions! (Error: ${?})"
 fi
 
-#MAILTO="daleconnelly@kfai.org,mason@kfai.org,dklann@broadcasttool.com"
 MAILTO="dklann@broadcasttool.com"
 
 # Gather all the services from Rivendell.
@@ -56,24 +109,32 @@ today=${TODAY:-$(strftime "%A" ${EPOCHSECONDS})}
 
 # For each service found:
 # Generate a log (-g) for tomorrow
-#   service: "Production" (-s)
+#   do not overwrite existing log unless we are called with --force (-P)
+#   service: (e.g.: "Production") (-s)
 #   merge traffic (-t)
 #   merge music (-m)
+#   day-spec (-d) is "tomorrow" (0) unless ${WHEN} is specified
 for service in ${services} ; do
-    ${RDLOGMANAGER} -s ${service} -g -t -m
+    ${RDLOGMANAGER} ${${FORCE:-"-P"}:+} -s ${service} -g -t -m -d ${WHEN:-0} 2>&1
 
-    # Create logs for Sunday and Monday as well if today is Friday.
+    # Also create logs for Sunday and Monday if ${today} is 'Friday'.
     if [[ ${today} == Friday ]] ; then
-	${RDLOGMANAGER} -s ${service} -g -t -m -d 1
-	${RDLOGMANAGER} -s ${service} -g -t -m -d 2
+	${RDLOGMANAGER} ${${FORCE:-"-P"}:+} -s ${service} -g -t -m -d 1 2>&1
+	${RDLOGMANAGER} ${${FORCE:-"-P"}:+} -s ${service} -g -t -m -d 2 2>&1
     fi
 done > ${outputFile}
 
-# Save a copy on the user's desktop.
-${CP} ${outputFile} ${HOME}/Desktop/RD-Log-Generate.txt
+# Save a copy in the user's Desktop folder if such a folder exists.
+if [[ -d ${HOME}/Desktop ]] ; then
+  ${CP} ${outputFile} ${HOME}/Desktop/RD-Log-Generate.txt
+fi
 
 # Send email to the addresses in $MAILTO with the same output as is on
 # the desktop.
-sendNotification ${0:t} ${MAILTO} LOG-GENERATE "Rivendell Logs have been generated." ${outputFile}
+if [[ -s ${outputFile} ]] ; then
+  sendNotification ${0:t} ${MAILTO} LOG-GENERATE "Rivendell Logs have been generated." ${outputFile}
+else
+  sendNotification ${0:t} ${MAILTO} LOG-GENERATE "rdlogmanager(1) created no output. Did it run? Better check on it."
+fi
 
 exit
