Refactor DEBUG file handling and logging.

diff --git a/usr/local/bin/btd-log-generate b/usr/local/bin/btd-log-generate
--- a/usr/local/bin/btd-log-generate
+++ b/usr/local/bin/btd-log-generate
@@ -29,7 +29,7 @@ zmodload zsh/datetime
 # This script complies with Semantic Versioning: http://semver.org/
 typeset -i v_major=0
 typeset -i v_minor=3
-typeset -i v_patch=9
+typeset -i v_patch=10
 typeset v_hash='$Hash$'
 
 typeset -i one_day=$((60 * 60 * 24))
@@ -195,20 +195,22 @@ if ((SHOW_VERSION)); then
     exit 0
 fi
 
-typeset tmp_file_stdout=/var/tmp/${0:t}-${USERNAME}.out
-typeset tmp_file_stderr=/var/tmp/${0:t}-${USERNAME}.err
-if [[ -f "${tmp_file_stdout}" ]] && ! [[ -w "${tmp_file_stdout}" ]]; then
-    ${LOGGER} --stderr -t "${0:t}" -p local7.err -i "ERROR: Unable to write output record '${tmp_file_stdout}'. Unable to continue."
-    exit 1
+if ((DEBUG)); then
+    typeset tmp_file_stdout=/var/tmp/${0:t}-${USERNAME}.out
+    typeset tmp_file_stderr=/var/tmp/${0:t}-${USERNAME}.err
+    if [[ -f "${tmp_file_stdout}" ]] && ! [[ -w "${tmp_file_stdout}" ]]; then
+        ${LOGGER} --stderr -t "${0:t}" -p local7.err -i "ERROR: Unable to write output record '${tmp_file_stdout}'. Unable to continue."
+        exit 1
+    fi
+    if [[ -f "${tmp_file_stderr}" ]] && ! [[ -w "${tmp_file_stderr}" ]]; then
+        ${LOGGER} --stderr -t "${0:t}" -p local7.err -i "ERROR: Unable to write output record '${tmp_file_stderr}'. Unable to continue."
+        exit 2
+    fi
+    exec 1> "${tmp_file_stdout}"
+    ${LOGGER} --stderr -t "${0:t}" -p local7.notice -i "NOTICE: writing standard output to '${tmp_file_stdout}'."
+    exec 2> "${tmp_file_stderr}"
+    ${LOGGER} --stderr -t "${0:t}" -p local7.notice -i "NOTICE: writing error output to '${tmp_file_stderr}'."
 fi
-if [[ -f "${tmp_file_stderr}" ]] && ! [[ -w "${tmp_file_stderr}" ]]; then
-    ${LOGGER} --stderr -t "${0:t}" -p local7.err -i "ERROR: Unable to write output record '${tmp_file_stderr}'. Unable to continue."
-    exit 2
-fi
-((DEBUG)) || exec 1> "${tmp_file_stdout}"
-${LOGGER} --stderr -t "${0:t}" -p local7.notice -i "NOTICE: writing standard output to '${tmp_file_stdout}'."
-((DEBUG)) || exec 2> "${tmp_file_stderr}"
-${LOGGER} --stderr -t "${0:t}" -p local7.notice -i "NOTICE: writing error output to '${tmp_file_stderr}'."
 
 if [[ -r /usr/bin/zsh-functions ]]; then
     source /usr/bin/zsh-functions
