Use getopt(1), add --verbose option and use it.

diff --git a/usr/local/bin/btd-dropbox-check b/usr/local/bin/btd-dropbox-check
--- a/usr/local/bin/btd-dropbox-check
+++ b/usr/local/bin/btd-dropbox-check
@@ -58,8 +58,9 @@ EOF
 # right-most components of the paths before returning them.
 getDropboxPaths() {
   local stationName=${1} ; shift
+  local verbose=${1} ; shift
 
-  local stationName
+  local whereClause
   local query="SELECT path FROM DROPBOXES"
   local -a paths
 
@@ -68,6 +69,8 @@ getDropboxPaths() {
   fi
 
   paths=( $(doSQL "${query}${whereClause:+${whereClause}}") )
+
+  (( verbose )) && echo "${0}: paths: ${paths}"
 
   # Output the paths with the 'basename' component stripped off. See
   # zshparam(1) for details.
@@ -78,8 +81,9 @@ getDropboxPaths() {
 # just the log paths for the named host.
 getDropboxLogPaths() {
   local stationName=${1} ; shift
+  local verbose=${1} ; shift
 
-  local stationName
+  local whereClause
   local query="SELECT log_path FROM DROPBOXES"
   local -a logPaths
 
@@ -88,6 +92,8 @@ getDropboxLogPaths() {
   fi
 
   logPaths=( $(doSQL "${query}${whereClause:+${whereClause}}") )
+
+  (( verbose )) && echo "${0}: logPaths: ${logPaths}"
 
   # Output the full log paths with the 'basename' component included.
   echo ${logPaths}
@@ -153,11 +159,32 @@ for C in ${ourCommands} ; do
 done
 ##################  END shell commands used in this script.  ##################
 
+VERBOSE=0
+
+TEMP=$(${GETOPT} -o hVv --long help,version,verbose -n "${0##*/}" -- "${@}")
+if (( ${?} != 0 )) ; then echo "Terminating..." >&2 ; return 1 ; fi
+# Note the quotes around ${TEMP}: they are essential!
+eval set -- "${TEMP}"
+while : ; do
+  case "${1}" in
+    -h|--help*) usage ${0##*/} ; exit ;;
+    -v|--verb*) VERBOSE=1 ; PASSFILE=none ; shift ;;
+    -V|--vers*) showVersion=1 ; shift ;;
+    --) shift ; break ;;
+    *) echo "Internal error!" >&2 ; return 1 ;;
+  esac
+done
+
+if ((showVersion)) ; then
+  echo "${0##*/}: version ${vMajor}.${vMinor}.${vPatch}-${${vHash#\$Hash: }%$}"
+  exit 0
+fi
+
 # Get all the dropbox paths for this host.
-local -a dropboxPaths dropboxLogPaths
-dropboxPaths=( $(getDropboxPaths $(rdGetStationName)) )
+typeset -a dropboxPaths dropboxLogPaths
+dropboxPaths=( $(getDropboxPaths $(rdGetStationName) ${VERBOSE}) )
 # Get all the dropbox log file paths for this host.
-dropboxLogPaths=( $(getDropboxLogPaths $(rdGetStationName)) )
+dropboxLogPaths=( $(getDropboxLogPaths $(rdGetStationName) ${VERBOSE}) )
 
 # Make sure the paths are accessible.
 for dir in ${dropboxPaths} ; do
