shellcheck
Fix showClock().

diff --git a/usr/local/bin/btd-clock-report b/usr/local/bin/btd-clock-report
--- a/usr/local/bin/btd-clock-report
+++ b/usr/local/bin/btd-clock-report
@@ -1,4 +1,12 @@
 #!/bin/zsh
+# shellcheck shell=bash disable=SC1105,SC2046,SC2079,SC2086,SC2089,SC2090,SC2154
+# SC1105: using (( )) correctly for ZSH
+# SC2046: we do not care about the word splitting in unquoted $() expansion
+# SC2079: ZSH arithmetic expressions can do floating point
+# SC2086: all instances of parameters are double-quoted the way I want them
+# SC2089: quotes are working the way we want
+# SC2090: quotes are working the way we want
+# SC2154: reference parameters are set by ZSH for us
 
 ##############################################################################
 ##############################################################################
@@ -22,7 +30,9 @@ colors
 # This script complies with Semantic Versioning: http://semver.org/
 vMajor=0
 vMinor=3
-vPatch=0
+vPatch=1
+# SC2016: $Hash is not a variable, it's a token that gets replaced by git(1)
+# shellcheck disable=SC2016
 vHash='$Hash$'
 
 ##############################################################################
@@ -73,7 +83,6 @@ validClock() {
 
 # Display all the events in one clock along with its title.
 showClock() {
-  local short_name="${1}" ; shift
   local full_name="${1}" ; shift
   local VERBOSE="${1}"
 
@@ -99,9 +108,9 @@ showClock() {
   eventCount="$(doSQL ${cQuery})"
   printf '%3d Events for Clock "%s"\n' "${eventCount}" "${full_name//_/ }"
 
-  # doSQL output is <TAB>-separated, make sure the whitespace in the
+  # doSQL() output is <TAB>-separated, make sure the whitespace in the
   # variable expansions below is a single <TAB>.
-  doSQL "${query}" | while read line ; do
+  doSQL "${query}" | while read -r line ; do
     eventName="${line%%	*}"
     eventDuration="${line##*	}"
     eventStart="${${line#*	}%	*}"
@@ -116,38 +125,45 @@ showClock() {
   return "${returnValue}"
 }
 
-################### BEGIN shell commands used in this script. ###################
+############# BEGIN external shell commands used in this script. #############
 # This script uses these 4 external commands.
 # Look for them in their upper case, parameter expanded form.
 typeset -a our_commands
 our_commands=( cat column fmt getopt )
-# Find the executables we need; this uses a little old fashioned shell and
-# a ZSH trick -- the (U) in the eval(1) says to evaluate the parameter as
-# all upper case letters. We will use the command names in upper case as
-# variables by which to call the external commands used in this script.
-for C in ${our_commands} ; do
+# Find the executables we need; this uses some basic shell and a ZSH trick:
+# the (U) in the eval says to evaluate the parameter as all upper case
+# letters. This snippet generates shell parameters representing the upper case
+# equivalent of the command names and sets the parameter values to the full path
+# of the commands.
+# Refresh this segment in Emacs by marking the appropriate region (or the whole
+# buffer with C-xH) and replacing it with C-uM-|mk-ourCommands (shell-command-on-region).
+for C in ${our_commands[*]} ; do
+  # shellcheck disable=SC2154 # ZSH: ${path} is set by the shell.
   for D in ${path} ; do
-    [[ -x "${D}/${C}" ]] && { eval "${(U)C//-/_}"="${D}/${C}" ; break }
+    # shellcheck disable=SC2140,SC2086 # we need the quotes
+    [[ -x "${D}/${C}" ]] && { eval "${(U)C//-/_}"="${D}/${C}" ; break ; }
   done
-  [[ -x $(eval print \$${(U)C//-/_}) ]] || { print "Cannot find ${C}! Done."; return 1 }
+  [[ -x $(eval print \$"${(U)C//-/_}") ]] || { print "Cannot find ${C}! Done."; return 1 ; }
 done
 unset our_commands
-#################### END shell commands used in this script. ####################
+############## END external shell commands used in this script. ##############
 
 # Get zsh functions necessary for this script.
-if [[ -r "${ROOT:-/}usr/local/bin/zsh-functions" ]] ; then
-  source "${ROOT:-/}usr/local/bin/zsh-functions"
+if [[ -r "/usr/local/bin/zsh-functions" ]] ; then
+  source "/usr/local/bin/zsh-functions"
+elif [[ -r "/usr/bin/zsh-functions" ]] ; then
+  source "/usr/bin/zsh-functions"
 else
-  exit $(error "Cannot read support library '${ROOT:-/}usr/local/bin/zsh-functions'. Please consult your astrologist!")
+  exit $(error "Cannot find support library 'zsh-functions'. Please consult your astrologist!")
 fi
 
 BOLD="${bold_color}"
 NORM="${reset_color}"
 
-# use getopt to parse the command line args
-TEMP=$(${GETOPT} -o ahvV --long all,help,verbose,version -n ${0:t} -- "${@}")
-if [ "${?}" != 0 ] ; then echo "${BOLD}Terminating...${NORM}" >&2 ; exit 1 ; fi
-# Note the quotes around "$TEMP": they are essential!
+if ! TEMP=$(${GETOPT} -o ahvV --long all,help,verbose,version -n ${0:t} -- "${@}") ; then
+  print "getopt(1) Fatal Error (${?}). Terminating..." >&2
+  return 1
+fi
 eval set -- "${TEMP}"
 while :
 do
@@ -174,11 +190,15 @@ if okDatabaseStructure CLOCKS:name+short_name ; then
   oIFS="${IFS}"
   IFS="	
 "
+  # SC2190: associative arrays behave differently in ZSH from Bash
+  # SC2207: mapfile behaves differently in ZSH from Bash
+  # shellcheck disable=SC2190,SC2207
   rivendellClockList=( $(doSQL "SELECT short_name,name FROM CLOCKS") )
   IFS="${oIFS}"
 else
   # Don't really know what else to do here...
   printf "Unknown database schema version (%03d). I give up." $(rdDatabaseVersion)
+  exit 1
 fi
 
 if (( SHOW_ALL )) ; then  
@@ -196,13 +216,15 @@ elif [[ -n "${1}" ]] ; then
   if [[ "${(L)1}" = 'list' ]] ; then
     echo "Current list of CLOCKs:"
     # (F) joins array elements with newline separator.
+    # SC2153: COLUMN is not a misspelling
+    # shellcheck disable=SC2153
     echo "${(F)rivendellClockList}" | "${COLUMN}" -x -c "${COLUMNS}"
-    read clock\?"Enter a Clock to list: "
+    read -r clock\?"Enter a Clock to list: "
   else
     clock="${1}"
   fi
 
-  if validClock "${rivendellClockList}" "${clock}" ; then
+  if validClock "${rivendellClockList[*]}" "${clock}" ; then
     showClock "${clock}" "${VERBOSE}"
   fi
 
