Add supporting function error() so things work when we call it.

diff --git a/usr/local/bin/btd-clock-report b/usr/local/bin/btd-clock-report
--- a/usr/local/bin/btd-clock-report
+++ b/usr/local/bin/btd-clock-report
@@ -26,37 +26,6 @@ vMinor=1
 vPatch=1
 vHash='$Hash$'
 
-#################  BEGIN shell commands used in this script.  #################
-# This script uses these 4 external commands.
-# Look for them in their upper case, parameter expanded form.
-ourCommands=(
-  cat
-  column
-  fmt
-  getopt
-)
-# Find the executables we need; this uses a little old fashioned shell and
-# a ZSH trick -- the (U) in the eval(1) says to evaluate the parameter as
-# all upper case letters. We will use the command names in upper case as
-# variables by which to call the external commands used in this script.
-for C in ${ourCommands} ; do
-  for D in ${path} ; do
-    [[ -x ${D}/${C} ]] && { eval ${(U)C//-/_}=${D}/${C} ; break }
-  done
-  [[ -x $(eval echo \$${(U)C//-/_}) ]] || { echo "Cannot find ${C}! Done."; return 1 }
-done
-##################  END shell commands used in this script.  ##################
-
-# Get zsh functions necessary for this script.
-if [[ -r ${ROOT:-/}usr/local/bin/zsh-functions ]] ; then
-  source ${ROOT:-/}usr/local/bin/zsh-functions
-else
-  exit $(error "Cannot read support library '${ROOT:-/}usr/local/bin/zsh-functions'. Please consult your astrologist!")
-fi
-
-BOLD="${bold_color}"
-NORM="${reset_color}"
-
 ##########################################################################################
 ## Locally defined subroutines
 ##########################################################################################
@@ -80,6 +49,19 @@ $(${FMT} <<<"Use the --html output to cause ${myName} to display the output suit
 $(${FMT} <<<"The --verbose option enables more chattiness in the operation. ${myName} sends diagnostic output to the standard error (STDERR) channel.")
 
 EOF
+}
+
+# Throw an error and return an unsuccessful return code.
+error() {
+  local message=${1}
+
+  ${FMT} >&2 <<EOF
+
+${RED}ERROR:${NORM} ${message}
+
+EOF
+  echo 254
+  return 254
 }
 
 # Convert milliseconds to HH:MM:SS with the hours and minutes zero-filled.
@@ -142,6 +124,37 @@ showClock() {
 
   return ${returnValue}
 }
+
+#################  BEGIN shell commands used in this script.  #################
+# This script uses these 4 external commands.
+# Look for them in their upper case, parameter expanded form.
+ourCommands=(
+  cat
+  column
+  fmt
+  getopt
+)
+# Find the executables we need; this uses a little old fashioned shell and
+# a ZSH trick -- the (U) in the eval(1) says to evaluate the parameter as
+# all upper case letters. We will use the command names in upper case as
+# variables by which to call the external commands used in this script.
+for C in ${ourCommands} ; do
+  for D in ${path} ; do
+    [[ -x ${D}/${C} ]] && { eval ${(U)C//-/_}=${D}/${C} ; break }
+  done
+  [[ -x $(eval echo \$${(U)C//-/_}) ]] || { echo "Cannot find ${C}! Done."; return 1 }
+done
+##################  END shell commands used in this script.  ##################
+
+# Get zsh functions necessary for this script.
+if [[ -r ${ROOT:-/}usr/local/bin/zsh-functions ]] ; then
+  source ${ROOT:-/}usr/local/bin/zsh-functions
+else
+  exit $(error "Cannot read support library '${ROOT:-/}usr/local/bin/zsh-functions'. Please consult your astrologist!")
+fi
+
+BOLD="${bold_color}"
+NORM="${reset_color}"
 
 # use getopt to parse the command line args
 TEMP=$(${GETOPT} -o ahvV --long all,html,verbose,version -n ${0:t} -- "${@}")
