Try harder to kill errant rdxport.cgi processes.

diff --git a/usr/local/bin/btd-dropbox-audit b/usr/local/bin/btd-dropbox-audit
--- a/usr/local/bin/btd-dropbox-audit
+++ b/usr/local/bin/btd-dropbox-audit
@@ -12,7 +12,7 @@ zmodload zsh/datetime
 # This script complies with Semantic Versioning: http://semver.org/
 declare -ri v_major=0
 declare -ri v_minor=1
-declare -ri v_patch=8
+declare -ri v_patch=9
 declare -r v_hash='$Hash$'
 
 # Prefer the instance in /usr/bin (that gets installed with the
@@ -50,26 +50,31 @@ function kill_with_privilege() {
     local -i pid
     local -ir attempt_limit=5
     local -i count=0
+    local sig=INT
     local -i return_value=0
     for pid ; do
 	while ((count < attempt_limit)) ; do
-	    ((VERBOSE)) && printf "Attempting to terminate process ID %d\n" "${pid}" >&2
-	    ${KILL} "${pid}"
+	    ((count > (attempt_limit/2))) && sig=KILL
+	    ((VERBOSE)) && printf "Attempting to terminate process ID %d with signal SIG%s..." "${pid}" "${sig}" >&2
+	    ${KILL} -"${sig}" "${pid}"
 	    ${SLEEP} 0.5
 	    if ! [[ -d "/proc/${pid}" ]] ; then
 		continue 2	# next pid in the for loop
 	    fi
-	    ${SUDO} "${KILL}" "${pid}"
+	    ((VERBOSE)) && printf "No go; attempting to terminate process ID %d with privileges using signal SIG%s... " "${pid}" "${sig}" >&2
+	    ${SUDO} "${KILL}" -"${sig}" "${pid}"
 	    ${SLEEP} 0.5
 	    if ! [[ -d "/proc/${pid}" ]] ; then
 		continue 2	# next pid in the for loop
 	    fi
 	    ${SLEEP} 0.5
+	    ((VERBOSE)) && print >&2
 	    ((count++))
 	done
-	printf 'Unable to terminate process %s. Please seek help!\n' "${pid}" >&2
+	printf '\nUnable to terminate process %s. Please seek help!\n' "${pid}" >&2
 	return_value=1
     done
+    ((VERBOSE && (count == attempt_limit))) && print >&2
     return "${return_value}"
 }
 
