Refactor for cleanliness. Update notification messages.

diff --git a/usr/local/bin/database-backup b/usr/local/bin/database-backup
--- a/usr/local/bin/database-backup
+++ b/usr/local/bin/database-backup
@@ -17,8 +17,13 @@ zmodload zsh/regex
 # This script complies with Semantic Versioning: http://semver.org/
 vMajor=0
 vMinor=1
-vPatch=4
+vPatch=5
 vHash='$Hash$'
+
+# Log STDOUT and STDERR of this script and all commands called by this
+# script to separate files.
+exec 1> /var/tmp/${0##*/}.out
+exec 2> /var/tmp/${0##*/}.err
 
 #################  BEGIN shell commands used in this script.  #################
 # This script uses these 10 external commands.
@@ -94,105 +99,116 @@ umask 0377
 # Dump each database into two separate files: one with data and one
 # without (to recreate an empty database).
 for database in ${databases} ; do
-    # Skip these databases.
-    [[ "${database}" =~ '(information|performance)_schema' ]] && continue
+  # Skip these databases.
+  [[ "${database}" =~ '(information|performance)_schema' ]] && continue
 
-    # Dump the database.
-    ${MYSQLDUMP} --defaults-file=${MY_CNF} --comments --dump-date ${masterData} --single-transaction --add-drop-database --add-drop-table --databases ${database} > ${DUMPDIR}/${database}-${TODAY}.sql
-    dbDumpVal=${?}
-    # Dump just the database schema.
-    ${MYSQLDUMP} --defaults-file=${MY_CNF} --comments --dump-date --no-data --databases ${database} > ${DUMPDIR}/${database}-SCHEMA-${TODAY}.sql
-    schemaDumpVal=${?}
+  # Dump the database.
+  ${MYSQLDUMP} --defaults-file=${MY_CNF} --comments --dump-date ${masterData} --single-transaction --add-drop-database --add-drop-table --databases ${database} > ${DUMPDIR}/${database}-${TODAY}.sql
+  dbDumpVal=${?}
+  # Dump just the database schema.
+  ${MYSQLDUMP} --defaults-file=${MY_CNF} --comments --dump-date --no-data --databases ${database} > ${DUMPDIR}/${database}-SCHEMA-${TODAY}.sql
+  schemaDumpVal=${?}
 
-    # Sanity checks for the output files.
-    if [[ -f ${DUMPDIR}/${database}-${TODAY}.sql ]] ; then
-      if ! [[ -s ${DUMPDIR}/${database}-${TODAY}.sql ]] ; then
-	${LOGGER} -t ${0:t} -p local7.err -i "Error dumping ${database}: ${DUMPDIR}/${database}-${TODAY}.sql exists but is empty (${dbDumpVal})."
-      fi
-    else
-      ${LOGGER} -t ${0:t} -p local7.err -i "Error dumping ${database}: ${DUMPDIR}/${database}-${TODAY}.sql was not created (${dbDumpVal})."
+  # Sanity checks for the output files.
+  if [[ -f ${DUMPDIR}/${database}-${TODAY}.sql ]] ; then
+    if ! [[ -s ${DUMPDIR}/${database}-${TODAY}.sql ]] ; then
+      ${LOGGER} -t ${0:t} -p local7.err -i "Error dumping ${database}: ${DUMPDIR}/${database}-${TODAY}.sql exists but is empty (${dbDumpVal})."
     fi
-    if [[ -f ${DUMPDIR}/${database}-SCHEMA-${TODAY}.sql ]] ; then
-      if ! [[ -s ${DUMPDIR}/${database}-SCHEMA-${TODAY}.sql ]] ; then
-	${LOGGER} -t ${0:t} -p local7.err -i "Error dumping Schema for ${database}: ${DUMPDIR}/${database}-SCHEMA-${TODAY}.sql exists but is empty (${schemaDumpVal})."
-      fi
-    else
-      ${LOGGER} -t ${0:t} -p local7.err -i "Error dumping Schema for ${database}: ${DUMPDIR}/${database}-SCHEMA-${TODAY}.sql was not created (${schemaDumpVal})."
+  else
+    ${LOGGER} -t ${0:t} -p local7.err -i "Error dumping ${database}: ${DUMPDIR}/${database}-${TODAY}.sql was not created (${dbDumpVal})."
+  fi
+  if [[ -f ${DUMPDIR}/${database}-SCHEMA-${TODAY}.sql ]] ; then
+    if ! [[ -s ${DUMPDIR}/${database}-SCHEMA-${TODAY}.sql ]] ; then
+      ${LOGGER} -t ${0:t} -p local7.err -i "Error dumping Schema for ${database}: ${DUMPDIR}/${database}-SCHEMA-${TODAY}.sql exists but is empty (${schemaDumpVal})."
     fi
+  else
+    ${LOGGER} -t ${0:t} -p local7.err -i "Error dumping Schema for ${database}: ${DUMPDIR}/${database}-SCHEMA-${TODAY}.sql was not created (${schemaDumpVal})."
+  fi
 done 2>&1 > ${DUMP_OUTPUT}
 
 # Do not proceed if there is output in $DUMP_OUTPUT (we had errors if
 # there is).
 if [[ -s ${DUMP_OUTPUT} ]] ; then
-    sendNotification "${0:t}" "${MAILTO}" DBDUMP-OUTPUT "Unexpectedly found messages in database dump log. See attached." ${DUMP_OUTPUT}
-else
-    if ${TAR} --create --bzip2 --atime-preserve --directory=${TMPDIR} --file ${TMPDIR}/mysql-backup-${TODAY}.tar.bz2 mysql ; then
-	# clean up after archiving the database dumps
-	if ${RM} -rf ${DUMPDIR} ; then
-	    # remove backup archives that are more than ${KEEP} days old
-	    if ${FIND} ${TMPDIR} -maxdepth 1 -iname mysql-backup-\*.tar.bz2 -mtime +${KEEP} -print -delete ; then
-		# successful purge, (optionally) make a backup of the backup
-		if [[ -n "${BACKUP_DIR}" ]] ; then
-		    if [[ -d ${BACKUP_DIR} ]] ; then
-		      ${RSYNC} --archive --temp-dir=${TMPDIR} --partial-dir=temp --delay-updates ${TMPDIR}/mysql-backup-* ${BACKUP_DIR}
-		      rsyncReturnValue=${?}
-		      if (( rsyncReturnValue == 0 || rsyncReturnValue == 23 || rsyncReturnValue == 24 )) ; then
-			# We cannot use the --delete option to
-			# rsync(1) because we are specifying
-			# individual files. Delete the backups
-			# "manually".
-			# As above: remove backup archives that are more than ${KEEP} days old
-			if ${FIND} ${BACKUP_DIR} -maxdepth 1 -iname mysql-backup-\*.tar.bz2 -mtime +${KEEP} -delete ; then
-			  : all seems well, move on
-			else
-			  sendNotification "${0:t}" "${MAILTO}" DBDUMP-RSYNC-CLEAN "Trouble deleting files from ${BACKUP_DIR} (${?}). Seek professional help!"
-			fi
-		      else
-			# These error messages are straight from the
-			# rsync(1) manual page (for rsync version
-			# 3.1.1).
-			case ${rsyncReturnValue} in
-			  1) message="Syntax or usage error" ;;
-			  2) message="Protocol incompatibility" ;;
-			  3) message="Errors selecting input/output files, dirs" ;;
-			  4) message="Requested action not supported (see rsync(1) manual page)." ;;
-			  5) message="Error starting client-server protocol" ;;
-			  6) message="Daemon unable to append to log-file" ;;
-			  10) message="Error in socket I/O" ;;
-			  11) message="Error in file I/O" ;;
-			  12) message="Error in rsync protocol data stream" ;;
-			  13) message="Errors with program diagnostics" ;;
-			  14) message="Error in IPC code" ;;
-			  20) message="Received SIGUSR1 or SIGINT" ;;
-			  21) message="Some error returned by waitpid()" ;;
-			  22) message="Error allocating core memory buffers" ;;
-			  23) message="Partial transfer due to error (quiet)" ;;
-			  24) message="Partial transfer due to vanished source files" ;;
-			  25) message="The --max-delete limit stopped deletions" ;;
-			  30) message="Timeout in data send/receive" ;;
-			  35) message="Timeout waiting for daemon connection" ;;
-			  *) message="Unknown rsync(1) return code" ;;
-			esac
-			if [[ ${message} =~ '.*\(quiet\)$' ]] ; then
-			  ${LOGGER} -t ${0:t} -p local7.notice -i "NOTICE: rsync returned ${rsyncReturnValue}."
-			else
-			  sendNotification "${0:t}" "${MAILTO}" DBDUMP-RSYNC "Trouble with making a backup of the backup of the database (rsync ERROR ${rsyncReturnValue} - ${message})."
-			fi
-			${LOGGER} -t ${0:t} -p local7.notice -i "NOTICE: rsync returned ${rsyncReturnValue} (${message})."
-		      fi
-		    else
-			sendNotification "${0:t}" "${MAILTO}" DBDUMP-BACKUP_DIR "Backup directory '${BACKUP_DIR}' does not exist and could not create it. (ERROR CODE ${?})."
-		    fi
-		fi
-	    else
-		sendNotification "${0:t}" "${MAILTO}" DBDUMP-AGING "Trouble removing backup archives (ERROR CODE ${?})."
-	    fi
-	else
-	    sendNotification "${0:t}" "${MAILTO}" DBDUMP-CLEANUP "Error removing '${DUMPDIR}' (ERROR CODE ${?})."
-	fi
-    else
-	sendNotification "${0:t}" "${MAILTO}" DBDUMP-TARBALL "Could not create tarball for MySQL database dumps in directory '${TMPDIR}' (ERROR CODE ${?})."
+  sendNotification "${0:t}" "${MAILTO}" DBDUMP-OUTPUT "Unexpectedly found messages in database dump log. See attached." ${DUMP_OUTPUT}
+  exit 1
+fi
+
+if ! ${TAR} --create --bzip2 --atime-preserve --directory=${TMPDIR} --file ${TMPDIR}/mysql-backup-${TODAY}.tar.bz2 mysql ; then
+  returnValue=${?}
+  sendNotification "${0:t}" "${MAILTO}" DBDUMP-TARBALL "Could not create tarball for MySQL database dumps in directory '${TMPDIR}' (ERROR CODE ${returnValue})."
+  exit ${returnValue}
+fi
+
+# clean up after archiving the database dumps
+if ! ${RM} -rf ${DUMPDIR} ; then
+  returnValue=${?}
+  sendNotification "${0:t}" "${MAILTO}" DBDUMP-CLEANUP "Error removing '${DUMPDIR}' (ERROR CODE ${returnValue})."
+  exit ${returnValue}
+fi
+
+# remove backup archives that are more than ${KEEP} days old
+if ! ${FIND} ${TMPDIR} -maxdepth 1 -iname mysql-backup-\*.tar.bz2 -mtime +${KEEP} -print -delete ; then
+  returnValue=${?}
+  sendNotification "${0:t}" "${MAILTO}" DBDUMP-AGING "Trouble removing backup archives (ERROR CODE ${returnValue})."
+  exit ${returnValue}
+fi
+
+# successful purge, (optionally) make a backup of the backup (if
+# BACKUP_DIR is set).
+if [[ -n "${BACKUP_DIR}" ]] ; then
+  if ! [[ -d ${BACKUP_DIR} ]] ; then
+    if ! ${MKDIR} -p ${BACKUP_DIR} ; then
+      returnValue=${?}
+      sendNotification "${0:t}" "${MAILTO}" DBDUMP-BACKUP_DIR "Backup directory '${BACKUP_DIR}' does not exist and could not create it. (ERROR CODE ${returnValue})."
+      exit ${returnValue}
     fi
+  fi
+  ${RSYNC} --archive --temp-dir=${TMPDIR} --partial-dir=temp --delay-updates ${TMPDIR}/mysql-backup-* ${BACKUP_DIR}
+  rsyncReturnValue=${?}
+  if (( rsyncReturnValue == 0 || rsyncReturnValue == 23 || rsyncReturnValue == 24 )) ; then
+    # We cannot use the --delete option to
+    # rsync(1) because we are specifying
+    # individual files. Delete the backups
+    # "manually".
+    # As above: remove backup archives that are more than ${KEEP} days old
+    if ! ${FIND} ${BACKUP_DIR} -maxdepth 1 -iname mysql-backup-\*.tar.bz2 -mtime +${KEEP} -delete ; then
+      returnValue=${?}
+      sendNotification "${0:t}" "${MAILTO}" DBDUMP-RSYNC-CLEAN "Trouble deleting files from ${BACKUP_DIR} (${returnValue}). Seek professional help!"
+      exit ${returnValue}
+    fi
+  else
+    # These error messages are straight from the
+    # rsync(1) manual page (for rsync version
+    # 3.1.1).
+    case ${rsyncReturnValue} in
+      1) message="Syntax or usage error" ;;
+      2) message="Protocol incompatibility" ;;
+      3) message="Errors selecting input/output files, dirs" ;;
+      4) message="Requested action not supported (see rsync(1) manual page)." ;;
+      5) message="Error starting client-server protocol" ;;
+      6) message="Daemon unable to append to log-file" ;;
+      10) message="Error in socket I/O" ;;
+      11) message="Error in file I/O" ;;
+      12) message="Error in rsync protocol data stream" ;;
+      13) message="Errors with program diagnostics" ;;
+      14) message="Error in IPC code" ;;
+      20) message="Received SIGUSR1 or SIGINT" ;;
+      21) message="Some error returned by waitpid()" ;;
+      22) message="Error allocating core memory buffers" ;;
+      23) message="Partial transfer due to error (quiet)" ;;
+      24) message="Partial transfer due to vanished source files" ;;
+      25) message="The --max-delete limit stopped deletions" ;;
+      30) message="Timeout in data send/receive" ;;
+      35) message="Timeout waiting for daemon connection" ;;
+      *) message="Unknown rsync(1) return code" ;;
+    esac
+    if [[ ${message} =~ '.*\(quiet\)$' ]] ; then
+      ${LOGGER} -t ${0:t} -p local7.notice -i "NOTICE: rsync returned ${rsyncReturnValue}."
+    else
+      sendNotification "${0:t}" "${MAILTO}" DBDUMP-RSYNC "Trouble with making a backup of the backup of the database (rsync ERROR ${rsyncReturnValue} - ${message})."
+    fi
+    ${LOGGER} -t ${0:t} -p local7.notice -i "NOTICE: rsync returned ${rsyncReturnValue} (${message})."
+  fi
 fi
 
 exit
