Robustness, --dry-run
Add more resiliance and robustness.

Add --dry-run (-D) option to show what would be done.

diff --git a/usr/local/bin/dyndns b/usr/local/bin/dyndns
--- a/usr/local/bin/dyndns
+++ b/usr/local/bin/dyndns
@@ -26,12 +26,13 @@ declare -r DO_API_KEY=$([[ -r ${HOME}/.config/doctl/api-access ]] && cat ${HOME}
 declare -r IP_ADDRESS_CACHE='/var/cache/public/last-known-public-ip'
 declare -i VERBOSE=0
 declare -i INTERACTIVE=0
+declare -i DRY_RUN=0
 declare -i FORCE=0
 
 # This script complies with Semantic Versioning: http://semver.org/
 declare -r vMajor=0
 declare -r vMinor=2
-declare -r vPatch=3
+declare -r vPatch=4
 # We can do this in one step in ZSH, but Bash needs 2 statements
 # And we do *not* want $Hash expanded yet.
 # shellcheck disable=SC2016
@@ -51,6 +52,7 @@ ${myName}: update DNS records for a non-static public IP address.
 Summary: ${myName##*/} [ --verbose (-v) ] [ --version (-V) ]
                 [ --help ] [ --interactive (-i) ]
                 [ --force ]
+                [ --dry-run (-D) ]
                 [ --domain (-d) <DOMAIN> ]
 		[ --hostname (-h) <HOSTNAME> ]
                 [ --ipv6 (-6) ]
@@ -86,6 +88,9 @@ ${myName} always attempts to update both the IPv4 address record
 ('A'), and the IPv6 address record ('AAAA') for the invoking
 host. ${myName} simply skips the 'AAAA' record update if it cannot
 determine the host's IPv6 address.
+
+Use the --dry-run (short option, -D) option to tell what would happen
+without doing it.
 
 Use the --force (short option, -f) option to force an update to the domain
 record.
@@ -147,25 +152,20 @@ get_domain_record_id() {
   fi
 }
 
-# is_cache_valid compares the retrieved IP address with the cached IP
-# address. Returns true (Zero) if they are the same, else false (non-Zero).
-is_cache_valid() {
-
-}
-
 ##############################################################################
 ##############################################################################
 ##     SCRIPT       MAIN       LINE
 ##############################################################################
 ##############################################################################
 
-if ! TEMP=$(getopt -o d:fh:iVv --long domain:,force,hostname:,interactive,help,version,verbose -n "${0##*/}" -- "${@}") ; then
+if ! TEMP=$(getopt -o Dd:fh:iVv --long dry-run,domain:,force,hostname:,interactive,help,version,verbose -n "${0##*/}" -- "${@}") ; then
   printf 'getopt(1) Fatal Error (%s). Terminating...\n' "${?}" >&2
   exit 1
 fi
 eval set -- "${TEMP}"
 while : ; do
   case "${1}" in
+    -D|--dry-run) DRY_RUN=1 ; shift ;;
     -d|--domain) DOMAIN="${2}" ; shift 2 ;;
     -f|--force) FORCE=1 ; shift ;;
     -h|--host*) THE_HOST_NAME="${2}" ; shift 2 ;;
@@ -192,30 +192,41 @@ fi
 ((VERBOSE)) && set -o xtrace
 ((VERBOSE > 1)) && set -o errtrace functrace
 
-declare -r API_BASE_ROUTE="/v2/domains/${DOMAIN}/records"
-
 # This hostname/domain was the original purpose of this script.
 DOMAIN="${DOMAIN:-btd.support}"
-THE_HOST_NAME="${THE_HOST_NAME:-changeme}"
+if [[ -z "${THE_HOST_NAME}" ]] ; then
+  printf "%s: Need a host name for dynamic DNS to work." "${0##*/}"
+  exit 2
+fi
+
+declare -r API_BASE_ROUTE="/v2/domains/${DOMAIN}/records"
 
 # Our last-known public IP address(es) is(are) cached in local storage. The
-# cache consists of one or (at most) two lines. The first line shoult be the
+# cache consists of one or (at most) two lines. The first line must be the
 # IPv4 address, the optional second line is the IPv6 address.
 declare -a cached_ip_list
-# SC2046: we *want* words to be split.
-# shellcheck disable=SC2046
-mapfile -t cached_ip_list <<<$(grep -v '^#' "${IP_ADDRESS_CACHE}" | tr -d '\012')
+if [[ -s "${IP_ADDRESS_CACHE}" ]] ; then
+  # SC2046: we *want* words to be split.
+  # shellcheck disable=SC2046
+  mapfile -t cached_ip_list <<<$(grep -v '^#' "${IP_ADDRESS_CACHE}" | tr -d '\012')
+fi
 
-# Hit David Klann's personal server to get the current public IPv4
-# and IPv6 addresses.
+# Hit the server at WHATS_MY_IP_URL to get the current public IPv4 and IPv6
+# addresses.
 current_ipv4=$(curl -4 --silent -o - "${WHATS_MY_IP_URL}")
 current_ipv6=$(curl -6 --silent -o - "${WHATS_MY_IP_URL}")
 
+# Empty IP address cache: create it with the IPv4 (and optionally, the IPv6)
+# address.
 if [[ -z "${cached_ip_list[0]}" ]] ; then
   # Maybe the first time doing this? Be sure /var/cache/public is
-  # world writeable!
+  # world writeable before running this script!
   if [[ -n "${current_ipv4}" ]] ; then
-    printf '%s\n' "${current_ipv4}" > "${IP_ADDRESS_CACHE}"
+    if ((DRY_RUN)) ; then
+      printf "Would have added IPv4 '%s' to '%s'\n" "${current_ipv4}" "${IP_ADDRESS_CACHE}"
+    else
+      printf '%s\n' "${current_ipv4}" > "${IP_ADDRESS_CACHE}"
+    fi
   else
     printf '%s: unable to get our current Public IPv4 address, and no known previous IPv4 address. Bad News!\n' "${0##*/}" >&2
     exit 3
@@ -226,14 +237,18 @@ if [[ -z "${cached_ip_list[1]}" ]] ; then
   # current_ipv6 is not set. It depends on whether the invoking host
   # *has* an inet6 address.
   if [[ -n "${current_ipv6}" ]] ; then
-    typeset -r temp_file="$(mktemp)"
-    # SC2064: I *want* this parameter expanded now.
-    # shellcheck disable=SC2064
-    trap "rm -f ${temp_file} ; exit ;" 0
-    (
-      head -n 1 "${IP_ADDRESS_CACHE}"
-      printf '%s\n' "${current_ipv6}"
-    ) > "${temp_file}" && mv "${temp_file}" "${IP_ADDRESS_CACHE}"
+    if ((DRY_RUN)) ; then
+      printf "Would have updated '%s' with '%s'\n" "${IP_ADDRESS_CACHE}" "${current_ipv6}"
+    else
+      typeset -r temp_file="$(mktemp)"
+      # SC2064: I *want* this parameter expanded now.
+      # shellcheck disable=SC2064
+      trap "rm -f ${temp_file} ; exit ;" 0
+      (
+	head -n 1 "${IP_ADDRESS_CACHE}"
+	printf '%s\n' "${current_ipv6}"
+      ) > "${temp_file}" && mv "${temp_file}" "${IP_ADDRESS_CACHE}"
+    fi
   fi
 fi
 
@@ -249,7 +264,11 @@ fi
 if ((FORCE)) || [[ "${cached_ip_list[0]}" != "${current_ipv4}" ]] ; then
 
   # Save this new IP address in the cache.
-  printf '%s\n' "${current_ipv4}" > "${IP_ADDRESS_CACHE}"
+  if ((DRY_RUN)) ; then
+    printf "Would have added '%s' to '%s'.\n" "${current_ipv4}" "${IP_ADDRESS_CACHE}"
+  else
+    printf '%s\n' "${current_ipv4}" > "${IP_ADDRESS_CACHE}"
+  fi
 
   # Get the 'A' record ID from D.O. This is a fatal error because we
   # only know how to *update* existing records (as of this version of
@@ -269,16 +288,20 @@ if ((FORCE)) || [[ "${cached_ip_list[0]}" != "${current_ipv4}" ]] ; then
     exit 1
   fi
 
-  # Update the 'A' record for this hostname.
-  # https://docs.digitalocean.com/reference/api/api-reference/#operation/patch_update_domain_record
-  # (documentation link updated Tue May 10 06:28:40 AM CDT 2022)
-  if ! RESPONSE=$(do_curl PUT "${API_BASE_ROUTE}/${A_RECORD_ID}" '{"data":"'"${current_ipv4}"'"}') ||
-     ! [[ "${RESPONSE}" =~ .*${A_RECORD_ID}.* ]] ; then
-    curl_exit_value="${?}"
-    ((VERBOSE)) && printf '"%s: unable to update domain record %s (%d).\n' \
-			  "${0##*/}" "${A_RECORD_ID}" "${curl_exit_value}" >&2
-    ((VERBOSE)) && printf 'response: %s\n' "${RESPONSE}" >&2
-    exit "${curl_exit_value}"
+  if ((DRY_RUN)) ; then
+    printf "Would have updated A record '%s' at Digital Ocean.\n" "${A_RECORD_ID}"
+  else
+    # Update the 'A' record for this hostname.
+    # https://docs.digitalocean.com/reference/api/api-reference/#operation/patch_update_domain_record
+    # (documentation link updated Tue May 10 06:28:40 AM CDT 2022)
+    if ! RESPONSE=$(do_curl PUT "${API_BASE_ROUTE}/${A_RECORD_ID}" '{"data":"'"${current_ipv4}"'"}') ||
+	! [[ "${RESPONSE}" =~ .*${A_RECORD_ID}.* ]] ; then
+      curl_exit_value="${?}"
+      ((VERBOSE)) && printf '"%s: unable to update domain record %s (%d).\n' \
+			    "${0##*/}" "${A_RECORD_ID}" "${curl_exit_value}" >&2
+      ((VERBOSE)) && printf 'response: %s\n' "${RESPONSE}" >&2
+      exit "${curl_exit_value}"
+    fi
   fi
 else
   ((VERBOSE)) && printf '%s: No change in IPv4 address %s\n' "${0##*/}" "${current_ipv4}" >&2
@@ -287,15 +310,19 @@ fi
 # address.
 if ((FORCE)) || [[ -n "${cached_ip_list[1]}" ]] && [[ "${cached_ip_list[1]}" != "${current_ipv6}" ]] ; then
 
-  # Save this new IPv6 address in the cache.
-  typeset -r temp_file="$(mktemp)"
-  # SC2064: I *want* this parameter expanded now.
-  # shellcheck disable=SC2064
-  trap "rm -f ${temp_file} ; exit ;" 0
-  (
-    head -n 1 "${IP_ADDRESS_CACHE}"
-    printf '%s\n' "${current_ipv6}"
-  ) > "${temp_file}" && mv "${temp_file}" "${IP_ADDRESS_CACHE}"
+  if ((DRY_RUN)) ; then
+    printf "Would have added IPv6 address '%s' to '%s'\n" "${current_ipv6}" "${IP_ADDRESS_CACHE}"
+  else
+    # Save this new IPv6 address in the cache.
+    typeset -r temp_file="$(mktemp)"
+    # SC2064: I *want* this parameter expanded now.
+    # shellcheck disable=SC2064
+    trap "rm -f ${temp_file} ; exit ;" 0
+    (
+      head -n 1 "${IP_ADDRESS_CACHE}"
+      printf '%s\n' "${current_ipv6}"
+    ) > "${temp_file}" && mv "${temp_file}" "${IP_ADDRESS_CACHE}"
+  fi
 
   # Get the 'AAAA' record ID from D.O. This is not a fatal problem.
   # TODO: create a new AAAA record if we have an IPv6 address.
@@ -305,16 +332,20 @@ if ((FORCE)) || [[ -n "${cached_ip_list[1]}" ]] && [[ "${cached_ip_list[1]}" != 
     printf '%s: WARNING: unable to get domain "AAAA" record ID.\n' "${0##*/}" >&2
   fi
 
-  # Update the 'AAAA' record for this hostname if we have an existing one.
-  # https://developers.digitalocean.com/documentation/v2/#update-a-domain-record
-  if [[ -n "${AAAA_RECORD_ID}" ]] ; then
-    if ! RESPONSE=$(do_curl PUT "${API_BASE_ROUTE}/${AAAA_RECORD_ID}" '{"data":"'"${current_ipv6}"'"}') ||
-	! [[ "${RESPONSE}" =~ .*${AAAA_RECORD_ID}.* ]] ; then
-      curl_exit_value="${?}"
-      ((VERBOSE)) && printf '"%s: unable to update domain record %s (%d).\n' \
-			    "${0##*/}" "${AAAA_RECORD_ID}" "${curl_exit_value}" >&2
-      ((VERBOSE)) && printf 'response: %s\n' "${RESPONSE}" >&2
-      exit "${curl_exit_value}"
+  if ((DRY_RUN)) ; then
+    printf "Would have updated AAAA record '%s' at Digital Ocean.\n" "${AAAA_RECORD_ID}"
+  else
+    # Update the 'AAAA' record for this hostname if we have an existing one.
+    # https://developers.digitalocean.com/documentation/v2/#update-a-domain-record
+    if [[ -n "${AAAA_RECORD_ID}" ]] ; then
+      if ! RESPONSE=$(do_curl PUT "${API_BASE_ROUTE}/${AAAA_RECORD_ID}" '{"data":"'"${current_ipv6}"'"}') ||
+	  ! [[ "${RESPONSE}" =~ .*${AAAA_RECORD_ID}.* ]] ; then
+	curl_exit_value="${?}"
+	((VERBOSE)) && printf '"%s: unable to update domain record %s (%d).\n' \
+			      "${0##*/}" "${AAAA_RECORD_ID}" "${curl_exit_value}" >&2
+	((VERBOSE)) && printf 'response: %s\n' "${RESPONSE}" >&2
+	exit "${curl_exit_value}"
+      fi
     fi
   fi
 else
