Add better handling of unreadable zsh-functions.

diff --git a/usr/local/bin/kuchota b/usr/local/bin/kuchota
--- a/usr/local/bin/kuchota
+++ b/usr/local/bin/kuchota
@@ -28,7 +28,11 @@ vPatch=2
 vHash='$Hash$'
 
 # Get zsh functions necessary for this script.
-[[ -r ${ROOT:-/}usr/local/bin/zsh-functions ]] && source ${ROOT:-/}usr/local/bin/zsh-functions
+if [[ -r ${ROOT:-/}usr/local/bin/zsh-functions ]] ; then
+  source ${ROOT:-/}usr/local/bin/zsh-functions
+else
+  exit $(error "Cannot read support library '${ROOT:-/}usr/local/bin/zsh-functions'. Please consult your tarot card reader!")
+fi
 
 ##########################################################################################
 ## Locally defined subroutines
