Fix some variable names, Add a delete procedure, Convert to a menu-based loop...

diff --git a/usr/local/bin/pmw-podget b/usr/local/bin/pmw-podget
--- a/usr/local/bin/pmw-podget
+++ b/usr/local/bin/pmw-podget
@@ -51,46 +51,145 @@ EOF
 }
 
 addOrReplaceFeed() {
-  local group=${1:?"${BOLD}Need a group name.${NORM}"} ; shift
-  local name=${1:?"${BOLD}Need a podcast feed name.${NORM}"} ; shift
-  local url=${1:?"${BOLD}Need a URL for the feed ${name}.${NORM}"} ; shift
-  local feedUser=${1}
-  local feedPass=${2}
+  local myName=${1} ; shift
+  local verbose=${1} ; shift
 
-  local tmpfile=$(mktemp)
-  trap "rm -f ${tmpfile}; exit;" 0 1 2 3
+  read feedURL\?"Type or paste the RSS feed URL for this podcast: "
+
+  read -q ok\?"Does this podcast download require a username? [y,N] "
+  echo
+  if [[ "${ok}" = y ]] ; then
+    read feedUser\?"Enter the feed username: "
+
+    read -q ok\?"Does this URL require a password for the user ${feedUser}? [y,N] "
+    echo
+    if [[ "${ok}" = y ]] ; then
+      read feedPassword\?"Enter the password for the user ${feedUser}: "
+    fi
+
+    protocol=${feedURL%://*}
+    hostANDport=${${feedURL#${protocol}://}%%/*}
+    route=${feedURL#${protocol}://${hostANDport}}
+
+    # ${urlWithCredentials} is used below only to try to obtain the feed title.
+    urlWithCredentials=${protocol}://${feedUser}${feedPassword:+:${feedPassword}}@${hostANDport}/${route}
+  fi
+
+  titleParserXSL=$(makeParser /rss/channel/title)
+  trap "${RM} -f ${titleParserXSL} ; exit ;" 0 1 2 3
+
+  ##########################################################################################
+  ## Get the feed title, either by its own XML (with xsltproc), or by
+  ## brute force with (wget). This code snippet and the XSL parser
+  ## snippet lifted from bashpodder, http://www.lincgeek.org/bashpodder/
+  ## (link retrieved Tue Aug 9 11:27:36 CDT 2016)
+  ##########################################################################################
+  feedTitle=$(${XSLTPROC} ${titleParserXSL} "${urlWithCredentials:-${feedURL}}" 2>/dev/null ||
+		 wget -q "${urlWithCredentials:-${feedURL}}" -O - | grep -m 1 '<title>' | sed -e 's,^ *<title>\(.*\)</title>.*$,\1,')
+  if [[ -z "${feedTitle}" ]] ; then
+
+    # Try it without the username and password.
+    if [[ -n "${urlWithCredentials}" ]] ; then
+
+      feedTitle=$(${XSLTPROC} ${titleParserXSL} "${feedURL}" 2>/dev/null ||
+		     wget -q "${feedURL}" -O - | grep -m 1 '<title>' | sed -e 's,^ *<title>\(.*\)</title>.*$,\1,')
+
+    else
+
+      warning "I could not discern the title for this feed. Please make sure the URL, username (if needed) and password (if needed) are correct and if necessary, re-run ${0##*/}."
+
+    fi
+  fi
+
+  ${RM} -f ${titleParserXSL}
+  trap "" 0 1 2 3
+
+  ##########################################################################################
+  ## Prompt for a name, use the feed title previously obtained if the
+  ## user does not enter anything.
+  ##########################################################################################
+  read name\?"Enter a name for this podcast (${BOLD}Note: I may do some manipulation of the name${NORM}): ${feedTitle:+[${feedTitle}]} "
+  [[ -z "${name}" ]] && name=${feedTitle}
+  # From the inside out, this parameter substitution does the following:
+  #    converts ":", "<Space>", ",", and "!" to a dash ("-")
+  #    deletes single (') and double (") quotes
+  #    converts double-dash ("--") to single dash ("-")
+  #    deletes a single dash ("-") at the end of the string
+  read -q ok\?"Using ${${${${name//[: ,\!)(]/-}//[\"\']/}//--/-}/%-/} for the podcast name. OK? [y,N]: "
+  until [[ ${ok} = y ]] ; do
+
+    read name\?"OK, try again. Enter a name for this podcast: "
+    read -q ok\?"Using '${${${${name//[: ,\!)(]/-}//[\"\']/}//--/-}/%-/}' for the podcast name. OK? [y,N]: "
+    echo
+
+  done
+  feedName="${${${${name//[: ,\!)(]/-}//[\"\']/}//--/-}/%-/}"
+
+  ##########################################################################################
+  ## Get the "category" for this podcast. Use a Rivendell GROUP for the category name.
+  ##########################################################################################
+  # See zsh-functions for the definition of doSQL.
+  rivendellGroupList=( $(doSQL "select NAME from GROUPS order by NAME") )
+
+  # List the groups and prompt them for a group to use if they asked for
+  # a list or if they did not name a group.
+  if [[ -z "${group}" ]] || [[ "${group}" =~ 'list' ]] ; then
+
+    echo "\nCurrent list of GROUPs:"
+    # The (F) modifier joins the array elements into a newline-separated string.
+    echo ${(F)rivendellGroupList} | ${COLUMN} -x -c $(( COLUMNS > 80 ? 78 : COLUMNS ))
+    read group\?"Type the name of the Rivendell GROUP into which this podcast will be imported: "
+
+  fi
+
+  # Validate the group against the current known list of groups in the
+  # Rivendell database.
+  until [[ "${rivendellGroupList}" =~ ".*${group}.*" ]] ; do
+
+    ${CAT} "ERROR: ${BOLD}${group} is not in the list. Please use a valid GROUP name.${NORM}"
+
+    echo "Current list of GROUPs:"
+    echo ${(F)rivendellGroupList} | ${COLUMN} -x -c $(( COLUMNS > 80 ? 78 : COLUMNS ))
+    read group\?"Enter the Rivendell GROUP into which this podcast will be imported: "
+
+  done
+
+  (( verbose )) && echo ${feedURL} ${group} ${feedName}${feedUser:+" USER:${feedUser}"}${feedPassword:+" PASS:${feedPassword}"}
 
   [[ -w ${DIR_CONFIG}/${CONFIG_SERVERLIST} ]] ||
     exit $(error "Missing access rights to modify the file ${DIR_CONFIG}/${CONFIG_SERVERLIST}")
 
+  local tmpfile=$(mktemp)
+  trap "${RM} -f ${tmpfile}; exit;" 0 1 2 3
+
   # Same group and name (possibly different URL?).
-  if ${GREP} -P -q "^[^#].*\s+${group}\s+${name}\s+" ${DIR_CONFIG}/${CONFIG_SERVERLIST} ; then
+  if ${GREP} -P -q "^[^#].*\s+${group}\s+${feedName}\s+" ${DIR_CONFIG}/${CONFIG_SERVERLIST} ; then
 
-    read -q ok\?"${name} already exists in group ${group}. Replace? [y,N] "
+    read -q ok\?"${feedName} already exists in group ${group}. Replace? [y,N] "
     if [[ "${ok}" = y ]] ; then
 
-      ${GREP} -P -v "^[^#].*\s+${group}\s+${name}\s+" ${DIR_CONFIG}/${CONFIG_SERVERLIST} > ${tmpfile}
+      ${GREP} -P -v "^[^#].*\s+${group}\s+${feedName}\s+" ${DIR_CONFIG}/${CONFIG_SERVERLIST} > ${tmpfile}
 
     fi
 
-  # Same name, different group.
-  elif ${GREP} -P -q "^[^#].*\s+${name}\s+" ${DIR_CONFIG}/${CONFIG_SERVERLIST} ; then
+    # Same name, different group.
+  elif ${GREP} -P -q "^[^#].*\s+${feedName}\s+" ${DIR_CONFIG}/${CONFIG_SERVERLIST} ; then
 
-    read -q ok\?"${name} already exists in a different group. Replace? [y,N] "
+    read -q ok\?"${feedName} already exists in a different group. Change to group '${group}'? [y,N] "
     if [[ "${ok}" = y ]] ; then
 
-      ${GREP} -P -v "^[^#].*\s+${name}\s+" ${DIR_CONFIG}/${CONFIG_SERVERLIST} > ${tmpfile}
+      ${GREP} -P -v "^[^#].*\s+${feedName}\s+" ${DIR_CONFIG}/${CONFIG_SERVERLIST} > ${tmpfile}
 
     fi
 
-  # New feed.
+    # New feed.
   else
 
     ${CP} ${DIR_CONFIG}/${CONFIG_SERVERLIST} ${tmpfile} ||
       exit $(error "Could not make a copy of ${DIR_CONFIG}/${CONFIG_SERVERLIST} (${?}). Bailing out.")
 
     ${CAT} >> ${tmpfile} <<EOF
-${url} ${group} ${name}${feedUser:+" USER:${feedUser}"}${feedPass:+" PASS:${feedPass}"}
+${feedURL} ${group} ${feedName}${feedUser:+" USER:${feedUser}"}${feedPass:+" PASS:${feedPass}"}
 EOF
 
   fi
@@ -103,13 +202,98 @@ EOF
 
     ${CHMOD} 644 ${DIR_CONFIG}/${CONFIG_SERVERLIST}
 
-    ${MKDIR} ${DIR_LIBRARY}/${group}/${name} ||
-      exit $(error "ERROR: failed to create new podcast directory ${DIR_LIBRARY}/${group}/${name}. (${?}).")
+    ${MKDIR} ${DIR_LIBRARY}/${group}/${feedName} ||
+      exit $(error "ERROR: failed to create new podcast directory ${DIR_LIBRARY}/${group}/${feedName}. (${?}).")
+
+  fi
+
+  cat <<EOF
+
+Podcast added. Now set up a Rivendell dropbox, and paste the path
+
+  ${DIR_LIBRARY}${group}${feedName}/*.mp3
+
+in the "Path Spec" field in rdadmin->Manage Hosts->HOST->Dropbox Configuration.
+
+EOF
+
+  trap "" 0 1 2 3
+}
+
+deleteFeed() {
+  local myName=${1} ; shift
+  local verbose=${1} ; shift
+
+  local tmpfile=$(mktemp)
+  trap "${RM} -f ${tmpfile}; exit;" 0 1 2 3
+
+  local feedList=( $(${GREP} -v '^#' ${DIR_CONFIG}/${CONFIG_SERVERLIST} | ${AWK} '{print $3}') )
+  echo "Current list of podcast feeds:"
+  # The (F) modifier joins the array elements into a newline-separated string.
+  echo ${(F)feedList} | ${COLUMN} -x -c $(( COLUMNS > 80 ? 78 : COLUMNS ))
+  read feedName\?"Type or paste the name of the podcast you want to delete or disable: "
+
+  read -k 1 deleteOrDisable\?"Do you want to disable (d) or delete (D) '${feedName}'? "
+  until [[ "${deleteOrDisable}" =~ '[Dd]' ]] ; do
+    echo
+    read -k 1 deleteOrDisable\?"Please type a lower case 'd' for 'disable' or an upper case 'D' for 'delete' "
+  done
+
+  if [[ "${deleteOrDisable}" = 'd' ]] ; then
+
+    echo "Disabling '${feedName}' in the feed list... \c"
+
+    ${SED} -i.bak -e "/[[:space:]]${feedName}[[:space:]]/s/^/#DISABLED#/" ${DIR_CONFIG}/${CONFIG_SERVERLIST}
+    if (( $(${DIFF} -side-by-side --suppress-common-lines ${DIR_LOG}/${PODGET_RUNTIME_DATA} ${DIR_LOG}/${PODGET_RUNTIME_DATA}.bak) == 1 )) ; then
+
+      ${RM} -f ${DIR_CONFIG}/${CONFIG_SERVERLIST}.bak
+      echo "Done."
+
+    else
+
+      warning "Could not properly disable the podcast feed '${feedName}'.
+
+Please fix the file '${DIR_CONFIG}/${CONFIG_SERVERLIST}' manually."
+
+      ${RM} -f ${DIR_CONFIG}/${CONFIG_SERVERLIST}.bak
+
+    fi
+
+  elif [[ "${deleteOrDisable}" = 'D' ]] ; then
+
+    echo "Deleting feed '${feedName}' from the feed list... \c"
+
+    ${GREP} -v "[[:space:]]${feedName}[[:space:]]" ${DIR_CONFIG}/${CONFIG_SERVERLIST} > ${tmpfile}
+
+    if [[ -s ${tmpfile} ]] ; then
+
+      if ${MV} ${tmpfile} ${DIR_CONFIG}/${CONFIG_SERVERLIST} ; then
+
+	echo "Done."
+
+      else
+
+	warning "Could not replace '${DIR_CONFIG}/${CONFIG_SERVERLIST}'
+with the deleted podcast feed. Do you have the access rights to
+replace this file?
+Please fix the file '${DIR_CONFIG}/${CONFIG_SERVERLIST}' manually."
+
+      fi
+    else
+
+      warning "Unable to find '${feedName}' in ${DIR_CONFIG}/${CONFIG_SERVERLIST}.
+
+Please fix the file ${DIR_CONFIG}/${CONFIG_SERVERLIST} manually."
+
+    fi
+  else
+
+    echo "\nWTF? How did you get past the prompt without entering a 'd' or a 'D'?"
 
   fi
 
   trap "" 0 1 2 3
-}  
+}
 
 makeParser() {
   local selection=${1:?"Need an XML selection."}
@@ -163,6 +347,7 @@ typeset -a ourCommands
 ourCommands=(
   cat
   chmod
+  column
   cp
   find
   fmt
@@ -212,7 +397,7 @@ while : ; do
 done
 
 if ((showVersion)) ; then
-  echo "${0##*/}: version ${vMajor}.${vMinor}.${vPatch}-${${vHash#\$Hash: }%\$}"
+  echo "${0##*/}: version ${vMajor}.${vMinor}.${vPatch}-${${vHash#\$Hash$}"
   exit 0
 fi
 
@@ -258,130 +443,52 @@ source ${DIR_CONFIG}/${CONFIG_CORE}
 ## The guts of why we are here.
 ##########################################################################################
 
-##########################################################################################
-read url\?"Enter or paste the RSS feed URL for this podcast: "
+typeset -a menu command
+typeset -R 2 count
 
-read -q ok\?"Does this URL require a username? [y,N] "
-echo
-if [[ "${ok}" = y ]] ; then
-  read feedUser\?"Enter the feed username: "
+while : ; do
+    count=0
 
-  read -q ok\?"Does this URL require a password for the user ${feedUser}? [y,N] "
-  echo
-  if [[ "${ok}" = y ]] ; then
-    read feedPassword\?"Enter the password for the user ${feedUser}: "
-  fi
+    menu=(
+      "Quit"
+      "Add or Replace a podcast feed"
+      "Delete a podcast feed"
+      "Show the complete list of podcast feeds"
+    )
+    command=(
+      'addOrReplaceFeed ${0##*/} ${verbose}'
+      'deleteFeed ${0##*/} ${verbose}'
+    )
 
-  protocol=${url%://*}
-  hostANDport=${${url#${protocol}://}%%/*}
-  route=${url#${protocol}://${hostANDport}}
+    for menuItem in ${menu} ; do
+	echo "${count}) $(eval echo ${menuItem})"
+	(( count++ ))
+    done
+    echo
 
-  # urlWithCredentials is only used below to try to obtain the feed title.
-  urlWithCredentials=${protocol}://${feedUser}${feedPassword:+:${feedPassword}}@${hostANDport}/${route}
-fi
+    read choice\?"Type your choice and press <Enter>: "
 
-titleParserXSL=$(makeParser /rss/channel/title)
-trap "${RM} -f ${titleParserXSL} ; exit ;" 0 1 2 3
+    echo
 
-##########################################################################################
-## Get the feed title, either by its own XML (with xsltproc), or by
-## brute force with (wget). This code snippet and the XSL parser
-## snippet lifted from bashpodder, http://www.lincgeek.org/bashpodder/
-## (link retrieved Tue Aug 9 11:27:36 CDT 2016)
-##########################################################################################
-feedTitle=$(${XSLTPROC} ${titleParserXSL} "${urlWithCredentials:-${url}}" 2>/dev/null ||
-	       wget -q "${urlWithCredentials:-${url}}" -O - | grep -m 1 '<title>' | sed -e 's,^ *<title>\(.*\)</title>.*$,\1,')
-if [[ -z "${feedTitle}" ]] ; then
+    if [[ -z "${choice}" ]] ; then
+	echo "Please enter a number between 0 and $(( count - 1 ))."
+    elif [[ ${choice} =~ '[0Qq]' ]] ; then
+	exit
+    elif [[ "${choice}" =~ '[[:space:]]*[[:alpha:]]{1,}' ]] ; then
+	echo "'${choice}' is not an option. Please enter a number between 0 and $(( count - 1 ))."
+    elif [[ "${choice}" =~ '[[:space:]]*[[:alnum:]]+[[:space:]]*' ]] ; then
+	echo "'${choice}' is not an option. Please enter a number between 0 and $(( count - 1 ))."
+    elif (( choice > 0 && choice < count )) ; then
+	eval $(echo ${command[${choice}]})
+    else
+	echo "'${choice}' is not an option. Please enter a number between 0 and $(( count - 1 ))."
+    fi
 
-  # Try it without the username and password.
-  if [[ -n "${urlWithCredentials}" ]] ; then
+    echo
 
-    feedTitle=$(${XSLTPROC} ${titleParserXSL} "${url}" 2>/dev/null ||
-		   wget -q "${url}" -O - | grep -m 1 '<title>' | sed -e 's,^ *<title>\(.*\)</title>.*$,\1,')
-
-  else
-
-    warning "I could not discern the title for this feed. Please make sure the URL, username (if needed) and password (if needed) are correct and if necessary, re-run ${0##*/}."
-
-  fi
-fi
-
-${RM} -f ${titleParserXSL}
-trap "" 0 1 2 3
-
-##########################################################################################
-## Prompt for a name, use the feed title previously obtained if the
-## user does not enter anything.
-##########################################################################################
-read name\?"Enter a name for this podcast (${BOLD}Note: I may do some manipulation of the name${NORM}): ${feedTitle:+[${feedTitle}]} "
-[[ -z "${name}" ]] && name=${feedTitle}
-# From the inside out, this parameter substitution does the following:
-#    converts ":", "<Space>", ",", and "!" to a dash ("-")
-#    deletes single (') and double (") quotes
-#    converts double-dash ("--") to single dash ("-")
-#    deletes a single dash ("-") at the end of the string
-read -q ok\?"Using ${${${${name//[: ,\!)(]/-}//[\"\']/}//--/-}/%-/} for the podcast name. OK? [y,N]: "
-until [[ ${ok} = y ]] ; do
-
-  read name\?"OK, try again. Enter a name for this podcast: "
-  read -q ok\?"Using '${${${${name//[: ,\!)(]/-}//[\"\']/}//--/-}/%-/}' for the podcast name. OK? [y,N]: "
-  echo
-
+    read -q choice\?"Press any key to continue: "
+    echo
 done
-feedName="${${${${name//[: ,\!)(]/-}//[\"\']/}//--/-}/%-/}"
-
-##########################################################################################
-## Get the "category" for this podcast. Use a Rivendell GROUP for the category name.
-##########################################################################################
-# See zsh-functions for the definition of doSQL.
-rivendellGroupList=( $(doSQL "select NAME from GROUPS order by NAME") )
-
-# List the groups and prompt them for a group to use if they asked for
-# a list or if they did not name a group.
-if [[ -z "${group}" ]] || [[ "${group}" =~ 'list' ]] ; then
-
-  echo "\nCurrent list of GROUPs:"
-  # The (F) modifier joins the array elements into a newline-separated string.
-  echo ${(F)rivendellGroupList} | column -x -c $(( COLUMNS > 80 ? 78 : COLUMNS ))
-  read group\?"Type the name of the Rivendell GROUP into which this podcast will be imported: "
-
-fi
-
-# Validate the group against the current known list of groups in the
-# Rivendell database.
-until [[ "${rivendellGroupList}" =~ ".*${group}.*" ]] ; do
-
-  ${CAT} "ERROR: ${BOLD}${group} is not in the list. Please use a valid GROUP name.${NORM}"
-
-  echo "Current list of GROUPs:"
-  echo ${(F)rivendellGroupList} | column -x -c $(( COLUMNS > 80 ? 78 : COLUMNS ))
-  read group\?"Enter the Rivendell GROUP into which this podcast will be imported: "
-
-done
-
-(( verbose )) && echo ${url} ${group} ${feedName}${feedUser:+" USER:${feedUser}"}${feedPassword:+" PASS:${feedPassword}"}
-
-##########################################################################################
-## Finally, add (or replace) the feed to the podget "serverlist" file
-## so that podget can retrieve the audio file and rdimport can
-## automatically import the file into the library.
-##########################################################################################
-addOrReplaceFeed \
-  ${group} \
-  ${feedName} \
-  "${url}" \
-  ${feedUser} \
-  ${feedPassword}
-
-cat <<EOF
-
-Podcast added. Now set up a Rivendell dropbox, and paste the path
-
-  ${DIR_LIBRARY}${group}${feedName}/*.mp3
-
-in the "Path Spec" field in rdadmin->Manage Hosts->HOST->Dropbox Configuration.
-
-EOF
 
 exit
 
