More cleanup.
Make launch curl(1) with --verbose for logging.
getopt --> ${GETOPT}

diff --git a/usr/local/bin/pmw-sage-rwt b/usr/local/bin/pmw-sage-rwt
--- a/usr/local/bin/pmw-sage-rwt
+++ b/usr/local/bin/pmw-sage-rwt
@@ -4,7 +4,7 @@
 # This script complies with Semantic Versioning: http://semver.org/
 vMajor=0
 vMinor=2
-vPatch=1
+vPatch=2
 # SC2016: $Hash is not a shell variable.
 # shellcheck disable=SC2016
 vHash='$Hash$'
@@ -80,10 +80,10 @@ EOF
 ##############################################################################
 
 ############# BEGIN external shell commands used in this script. #############
-# This script uses these 4 external commands.
+# This script uses these 5 external commands.
 # Look for them in their upper case, parameter expanded form.
 typeset -a our_commands
-our_commands=( cat curl logger ping )
+our_commands=( cat curl getopt logger ping )
 # Find the executables we need; this uses some basic shell and a ZSH trick:
 # the (U) in the eval says to evaluate the parameter as all upper case
 # letters. This snippet generates shell parameters representing the upper case
@@ -103,7 +103,7 @@ done
 unset our_commands C D
 ############## END external shell commands used in this script. ##############
 
-if ! TEMP=$(getopt -o hVv --long help,version,verbose -n "${0:t}" -- "${@}") ; then
+if ! TEMP=$(${GETOPT} -o hVv --long help,version,verbose -n "${0:t}" -- "${@}") ; then
   echo "getopt(1) Fatal Error (${?}). Terminating..." >&2
   return 1
 fi
@@ -116,7 +116,7 @@ while : ; do
     -v|--verb*) ((VERBOSE += 1)) ; shift ;;
     -V|--vers*) showVersion=1 ; shift ;;
     --) shift ; break ;;
-    *) echo "${0:t}: getopt internal error!. Terminating..." >&2 ; return 1 ;;
+    *) echo "${0:t}: ${GETOPT} internal error!. Terminating..." >&2 ; return 1 ;;
   esac
 done
 
@@ -128,17 +128,17 @@ fi
 ## Ensure we have all three command line parameters.
 if [[ -z "${1}" ]] ; then
   usage "${0}"
-  ${LOGGER} --stderr -t "${0:t}" -p local7.err -i  "ERROR: Missing host." 2>&1
+  ${LOGGER} --stderr -t "${0:t}" -p local7.err -i  "Error: Missing host."
   exit 125
 fi
 if [[ -z "${2}" ]] ; then
   usage "${0}"
-  ${LOGGER} --stderr -t "${0:t}" -p local7.err -i  "ERROR: Missing the device username." 2>&1
+  ${LOGGER} --stderr -t "${0:t}" -p local7.err -i  "Error: Missing the device username."
   exit 126
 fi
 if [[ -z "${3}" ]] ; then
   usage "${0}"
-  ${LOGGER} --stderr -t "${0:t}" -p local7.err -i  "ERROR: Missing the device password." 2>&1
+  ${LOGGER} --stderr -t "${0:t}" -p local7.err -i  "Error: Missing the device password."
   exit 127
 fi
 
@@ -158,14 +158,14 @@ exec 2> "/var/tmp/${0:t}.err"
 setopt xtrace
 
 if ! [[ -x ${CURL} ]] ; then
-  ${LOGGER} --stderr -t "${0:t}" -p local7.err -i  "ERROR: Cannot find curl command line app." 2>&1
+  ${LOGGER} --stderr -t "${0:t}" -p local7.err -i  "Error: Cannot find curl command line app."
   exit 2
 fi
 
 # SC2069: ZSH redirection is a little different than BASH
 # shellcheck disable=SC2069
 if ! ${PING} -q -c 1 -w 1 "${SAGEHOST}" 2>&1 > /dev/null ; then
-  ${LOGGER} --stderr -t "${0:t}" -p local7.err -i  "ERROR: cannot ping '${SAGEHOST}', will not continue." 2>&1
+  ${LOGGER} --stderr -t "${0:t}" -p local7.err -i  "Error: cannot ping '${SAGEHOST}', will not continue."
   exit 3
 fi
 
@@ -173,7 +173,7 @@ ${LOGGER} -t "${0:t}" -p local7.info -i -- "INFO: Running curl(1) to ${SAGEHOST}
 # SC2086 CURL is simply the full path to the executable, no quotes needed.
 # shellcheck disable=SC2086
 ${DEBUG} ${CURL} \
-	 --silent \
+	 --verbose \
 	 --output "${CURL_OUTPUT}" \
 	 --anyauth \
 	 --user "${SAGEUSER}:${SAGEPASS}" \
