Add command line parser for Service and Group, add usage(), make production-ready.

diff --git a/usr/local/bin/weekly-traffic b/usr/local/bin/weekly-traffic
--- a/usr/local/bin/weekly-traffic
+++ b/usr/local/bin/weekly-traffic
@@ -3,7 +3,6 @@
 ##########################################################################################
 ##########################################################################################
 ##
-##
 ## weekly-traffic
 ##
 ## A BTD tool to report on weekly traffic events.
@@ -22,8 +21,44 @@ colors
 # This script complies with Semantic Versioning: http://semver.org/
 vMajor=0
 vMinor=1
-vPatch=0
+vPatch=1
 vHash='$Hash$'
+
+#################  BEGIN shell commands used in this script.  #################
+# This script uses these 4 external commands.
+# Look for them in their upper case, parameter expanded form.
+ourCommands=(
+  cat
+  getopt
+  sort
+  tr
+)
+# Find the executables we need; this uses a little old fashioned shell and
+# a ZSH trick -- the (U) in the eval(1) says to evaluate the parameter as
+# all upper case letters. We will use the command names in upper case as
+# variables by which to call the external commands used in this script.
+for C in ${ourCommands} ; do
+  for D in ${path} ; do
+    [[ -x ${D}/${C} ]] && { eval ${(U)C//-/_}=${D}/${C} ; break }
+  done
+  [[ -x $(eval echo \$${(U)C//-/_}) ]] || { echo "Cannot find ${C}! Done."; return 1 }
+done
+##################  END shell commands used in this script.  ##################
+
+# Tell them how to use this command.
+usage() {
+    myName=${1}
+
+    ${CAT} << EOF
+${myName}: Generate a weekly traffic report for the week ending "yesterday".
+
+Summary: ${myName:t} --group (-g) <Traffic Group Name>
+                        --service (-s) <Service Name>
+
+Both the --group (-g) and --service (-s) parameters are required.
+
+EOF
+}
 
 # Get zsh functions necessary for this script.
 if [[ -r ${ROOT:-/}usr/local/bin/zsh-functions ]] ; then
@@ -32,7 +67,29 @@ else
   exit $(error "Cannot read support library '${ROOT:-/}usr/local/bin/zsh-functions'. Please consult your tarot card reader!")
 fi
 
-service="WDRT"
+# use getopt to parse the command line args
+TEMP=$(${GETOPT} -o hg:s:v --long help,group:,service:,version -n ${0:t} -- "${@}")
+if [[ ${?} != 0 ]] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+# Note the quotes around "$TEMP": they are essential!
+eval set -- "${TEMP}"
+while :
+do
+  case "${1}" in
+      -g|--grou*) group=${2} ; shift 2 ;;
+      -s|--serv*) service=${2} ; shift 2 ;;
+      -h|--help) usage ${0} ; exit ;;
+      -v|--vers*) showVersion=1 ; shift ;;
+      --) shift ; break ;;
+      *) echo "Internal error, cannot continue!" ; exit 1 ;;
+  esac
+done
+unset TEMP
+
+if ((showVersion)) ; then
+  echo "${0:t}: version ${vMajor}.${vMinor}.${vPatch}-${${vHash#\$Hash: }%$}"
+  exit 0
+fi
+
 typeset -A cartCount
 
 # Start date is midnight seven days ago.
@@ -47,7 +104,7 @@ selectCountStatement="SELECT
   COUNT(*)
   FROM ${service}_SRT
   WHERE cart_number IN
-  (SELECT number FROM CART WHERE group_name = 'TRAFFIC')
+  (SELECT number FROM CART WHERE group_name = '${group}')
   AND
   event_datetime > '${reportStartDate}'
   AND
@@ -66,7 +123,7 @@ selectStatement="SELECT
   event_datetime, title, cart_number, length/1000
   FROM ${service}_SRT
   WHERE cart_number IN
-  (SELECT number FROM CART WHERE group_name = 'TRAFFIC')
+  (SELECT number FROM CART WHERE group_name = '${group}')
   AND
   event_datetime > '${reportStartDate}'
   AND
@@ -93,11 +150,11 @@ doSQL "${selectStatement}" | while read line ; do
 done
 
 print "\nPerformance Totals:"
-printf "%6s: %3s %s\n" 'Cart #' 'Plays' 'Cart Title'
+printf "%6s\t%3s\t%s\n" 'Cart #' 'Plays' 'Cart Title'
 
-for cart in $(echo ${(k)cartCount} | tr ' ' '\012' | sort -n) ; do
+for cart in $(echo ${(k)cartCount} | ${TR} ' ' '\012' | ${SORT} -n) ; do
 
-  printf "%06d: %5d %s\n" ${cart} ${cartCount[${cart}]} "$(rdCartTitleFromNumber ${cart})"
+  printf "%06d\t%5d\t%s\n" ${cart} ${cartCount[${cart}]} "$(rdCartTitleFromNumber ${cart})"
 
 done
 
