Replace manual COMMAND VAR settings with programmatic settings in 2 functions, whitespace corrections.

diff --git a/usr/local/bin/zsh-functions b/usr/local/bin/zsh-functions
--- a/usr/local/bin/zsh-functions
+++ b/usr/local/bin/zsh-functions
@@ -203,10 +203,27 @@ doSQL() {
   local useMyCNF=0
   local usableMyCNF=4
   local rdconfig=${RD_CONFIG:-${ROOT:-/}etc/rd.conf}
-  local MYSQL=$(whence mysql) ; MYSQL=${MYSQL:-${ROOT:-/}usr/bin/mysql}
-  local AWK=$(whence awk) ; AWK=${AWK:-${ROOT:-/}usr/bin/awk}
-  local EGREP=$(whence egrep) ; EGREP=${EGREP:-${ROOT:-/}bin/egrep}
-  local SED=$(whence sed) ; SED=${SED:-${ROOT:-/}bin/sed}
+
+  #################  BEGIN shell commands used in this function.  #################
+  # This function uses these 4 external commands.
+  # Look for them in their upper case, parameter expanded form.
+  ourCommands=(
+    awk
+    egrep
+    mysql
+    sed
+  )
+  # Find the executables we need; this uses a little old fashioned shell and
+  # a ZSH trick -- the (U) in the eval(1) says to evaluate the parameter as
+  # all upper case letters. We will use the command names in upper case as
+  # variables by which to call the external commands used in this function.
+  for C in ${ourCommands} ; do
+    for D in ${path} ; do
+      [[ -x ${D}/${C} ]] && { eval ${(U)C//-/_}=${D}/${C} ; break }
+    done
+    [[ -x $(eval echo \$${(U)C//-/_}) ]] || { echo "Cannot find ${C}! Done."; return 1 }
+  done
+  ##################  END shell commands used in this function.  ##################
 
   typeset -gx _DB_HOST _DB_USER _DB_PWD _DB_DATABASE _USE_MYCNF
 
@@ -224,16 +241,16 @@ doSQL() {
     # BUG ALERT: this assumes the credentials in .my.cnf are relevant
     # to the Rivendell database.
     if [[ -r ~/.my.cnf ]] && [[ $(${EGREP} -c '^(database|host|user|password)' ~/.my.cnf) -ge 4 ]] ; then
-	cd -q			# Sigh, mapfile cannot deal with path components.
-	myCnfLines=( ${mapfile[.my.cnf]} )
+      cd -q			# Sigh, mapfile cannot deal with path components.
+      myCnfLines=( ${mapfile[.my.cnf]} )
 
-	# Need to check for each of these parameters in .my.cnf in
-	# order to be able to use it.
-	for parm in database host password user ; do
-	  if [[ "${myCnfLines}" =~ ${parm} ]] ; then
-	    (( useMyCNF++ ))
-	  fi
-	done
+      # Need to check for each of these parameters in .my.cnf in
+      # order to be able to use it.
+      for parm in database host password user ; do
+	if [[ "${myCnfLines}" =~ ${parm} ]] ; then
+	  (( useMyCNF++ ))
+	fi
+      done
     else
       # Horribly insecure, but this is the "Rivendell Way".
       if [[ -r ${rdconfig} ]] ; then
@@ -272,10 +289,26 @@ getMyIPAddresses() {
   local -a ipAddresses
   local returnValue=0
 
-  local AWK=$(whence awk) ; AWK=${AWK:-${ROOT:-/}usr/bin/awk}
-  local GREP=$(whence grep) ; GREP=${GREP:-${ROOT:-/}bin/grep}
-  local IP=$(whence ip) ; IP=${IP:-${ROOT:-/}sbin/ip}
-  local SED=$(whence sed) ; SED=${SED:-${ROOT:-/}bin/sed}
+  ################  BEGIN shell commands used in this function.  ################
+  # This function uses these 4 external commands.
+  # Look for them in their upper case, parameter expanded form.
+  ourCommands=(
+    awk
+    grep
+    ip
+    sed
+  )
+  # Find the executables we need; this uses a little old fashioned shell and
+  # a ZSH trick -- the (U) in the eval(1) says to evaluate the parameter as
+  # all upper case letters. We will use the command names in upper case as
+  # variables by which to call the external commands used in this function.
+  for C in ${ourCommands} ; do
+    for D in ${path} ; do
+      [[ -x ${D}/${C} ]] && { eval ${(U)C//-/_}=${D}/${C} ; break }
+    done
+    [[ -x $(eval echo \$${(U)C//-/_}) ]] || { echo "Cannot find ${C}! Done."; return 1 }
+  done
+  #################  END shell commands used in this function.  #################
 
   ipAddresses=( $(${IP} -o -4 addr show |
 		     ${GREP} -E -v '^(lo|virbr|tun)' |
