Add support for specification of 'quiet time' duration with NOTIFICATIONS_QUIET_TIME_DURATION to sendNotification() and notificationSent().

diff --git a/usr/local/bin/zsh-functions b/usr/local/bin/zsh-functions
--- a/usr/local/bin/zsh-functions
+++ b/usr/local/bin/zsh-functions
@@ -36,7 +36,7 @@ zmodload zsh/datetime
   vLibRelease=0
   vLibMajor=0
   vLibMinor=2
-  vLibPatch=26
+  vLibPatch=27
   vLibHash='$Hash$'
 }
 
@@ -127,7 +127,7 @@ function sendNotification() {
   local startTime="${EPOCHSECONDS}"
 
   # A notification was already sent for this ${type}, no need to continue.
-  if notificationSent "${myName}" "${type}" "${startTime}" ; then
+  if notificationSent "${myName}" "${type}" "${startTime}" ${NOTIFICATIONS_QUIET_TIME_DURATION:-$((60 * 60 * 24))} ; then
     return 0
   fi
 
@@ -190,65 +190,80 @@ EOF
   return ${returnValue}
 }
 
-# notificationSent records the type and time of a notification sent with
-# sendNotification().
+# notificationSent records the type and time of a notification sent
+# with sendNotification(). Knows about "quiet time" to avoid alert
+# fatigue.
 function notificationSent() {
   local theirName="${1}" ; shift
   local type="${1}" ; shift
-  local notificationTime="${1}"
+  local notificationTime="${1}"; shift
+  local -i quiet_time_duration="${1}"
 
   local SED=$(command -v sed) ; SED="${SED:-/bin/sed}"
   local notifyDB="${NOTIFY_DB:-/usr/local/etc/btd/notifications}"
   local notification
-  local foundPriorNotification=0
-  local oneDay=$(( 60 * 60 * 24 ))
-  local returnValue=1
+  local -i oneDay=$((60 * 60 * 24))
+  local -i foundPriorNotification=0
+  local -i returnValue=0 # Assume success.
 
-  # Is there a notification database?
-  if [[ -f "${notifyDB}" ]] ; then
-    while read -r notification ; do
-      if [[ "${notification%:*}" == "${theirName}:${type}" ]] ; then
-        foundPriorNotification=1
-        break
-      fi
-    done < "${notifyDB}"
-    # Have we seen this notification before?
-    if (( foundPriorNotification )) ; then
-      # Has it been more than a day since we last notified? Or, are we ignoring
-      # quiet times? (Set shell parameter NOTIFICATIONS_IGNORE_QUIET_TIME to any
-      # value to ignore "quiet time" and send the notification.
-      if (( (notificationTime - oneDay) > ${notification##*:} )) ||
-	   [[ -n "${NOTIFICATIONS_IGNORE_QUIET_TIME}" ]]; then
-        if ${SED} -i -e "s/^${theirName}:${type}:.*$/${theirName}:${type}:${notificationTime}/" "${notifyDB}" ; then
-          logit "${0}" 0 "${theirName} NOTICE: '${type}' notification UPDATED at $(strftime %F\ %T ${notificationTime})."
-        else
-          logit "${0}" 0 "${theirName} WARNING: Unable to UPDATE '${type}' notification at $(strftime %F\ %T ${notificationTime}) (${?})."
-          returnValue=2
-        fi
-      else
-        # It has been less than a day since we last notified. We are
-        # done here.
-        logit "${0}" 0 "${theirName} NOTICE: quiet time for notification '${type}' at $(strftime %F\ %T ${notificationTime}) ($(strftime %F\ %T ${notification##*:}))."
-        returnValue=0
-      fi
-    else
-      # This is a new notification for this ${theirName} and ${type}
-      if echo "${theirName}:${type}:${notificationTime}" >> "${notifyDB}" ; then
-        logit "${0}" 0 "${theirName} NOTICE: '${type}' notification added at $(strftime %F\ %T ${notificationTime})."
-      else
-        logit "${0}" 0 "${theirName} WARNING: Unable to APPEND '${type}' notification at $(strftime %F\ %T ${notificationTime}) (${?})."
-        returnValue=3
-      fi
+  if [[ -z "${quiet_time_duration}" ]] ; then
+    quiet_time_duration=${oneDay}
+  fi
+
+  # Is there a directory for the notification database?
+  if ! [[ -d "${notifyDB:h}" ]] ; then
+    if ! mkdir -p "${notifyDB:h}" ; then
+      returnValue="${?}"
+      logit "${0}" 0 "${theirName} WARNING: Unable to mkdir '${notifyDB:h}' (${returnValue})."
+      return "${returnValue}"
     fi
-  else
+  fi
+  if ! [[ -f "${notifyDB}" ]] ; then
     # No existing notification database, so create it and add this
     # notification to it.
-    if echo "${theirName}:${type}:${notificationTime}" > ${notifyDB} ; then
-      logit "${0}" 0 "${theirName} NOTICE: '${type}' notification created at $(strftime %F\ %T ${notificationTime})."
-    else
+    if ! printf '%s:%s:%d\n' "${theirName}" "${type}" "${notificationTime}" > ${notifyDB} ; then
       logit "${0}" 0 "${theirName} WARNING: Unable to CREATE '${type}' notification at $(strftime %F\ %T ${notificationTime}) (${?})."
-      returnValue=4
+      return 4
     fi
+  fi
+
+  # Scan the database for an existing notification.
+  logit "${0}" 0 "${theirName} NOTICE: '${type}' notification created at $(strftime %F\ %T ${notificationTime})."
+  while read -r notification ; do
+    if [[ "${notification%:*}" == "${theirName}:${type}" ]] ; then
+      foundPriorNotification=1
+      break
+    fi
+  done < "${notifyDB}"
+
+  if ! ((foundPriorNotification)) ; then
+    # This is a new notification for this ${theirName} and ${type},
+    # append it to the database.
+    if ! printf '%s:%s:%d\n' "${theirName}" "${type}" "${notificationTime}" >> "${notifyDB}" ; then
+      logit "${0}" 0 "${theirName} WARNING: Unable to APPEND '${type}' notification at $(strftime %F\ %T ${notificationTime}) (${?})."
+      return 3
+    fi
+    logit "${0}" 0 "${theirName} NOTICE: '${type}' notification added at $(strftime %F\ %T ${notificationTime})."
+    return
+  fi
+
+  # This is an additional ${type} of notification for ${theirName}.
+  if (( (notificationTime - quiet_time_duration) > ${notification##*:} )) ||
+       [[ -n "${NOTIFICATIONS_IGNORE_QUIET_TIME}" ]]; then
+    # It has been longer than ${quiet_time_duration} since we last
+    # notified, or are we ignoring quiet times. (Set shell parameter
+    # NOTIFICATIONS_IGNORE_QUIET_TIME to any value to ignore "quiet
+    # time" to send the notification.)
+    if ${SED} -i -e "s/^${theirName}:${type}:.*$/${theirName}:${type}:${notificationTime}/" "${notifyDB}" ; then
+      logit "${0}" 0 "${theirName} NOTICE: '${type}' notification UPDATED at $(strftime %F\ %T ${notificationTime})."
+    else
+      logit "${0}" 0 "${theirName} WARNING: Unable to UPDATE '${type}' notification at $(strftime %F\ %T ${notificationTime}) (${?})."
+      return 2
+    fi
+  else
+    # It has been less than ${quiet_time_duration} since we last
+    # notified, or we are honoring quiet time: we are done here.
+    logit "${0}" 0 "${theirName} NOTICE: quiet time for notification '${type}' at $(strftime %F\ %T ${notificationTime}) ($(strftime %F\ %T ${notification##*:}))."
   fi
 
   return "${returnValue}"
