Add zsh_library_version() test.

diff --git a/usr/local/bin/test-zsh-functions/zsh-functions b/usr/local/bin/test-zsh-functions/zsh-functions
--- a/usr/local/bin/test-zsh-functions/zsh-functions
+++ b/usr/local/bin/test-zsh-functions/zsh-functions
@@ -6,10 +6,13 @@
 # shellcheck disable=SC1090
 . ${DIR:-.}/zsh-functions
 
-#echo "Sending two notifications. Please wait... \c"
-#sendNotification test dklann@coldcrossing.com TEST "This is a test message."
-#sendNotification test dklann@coldcrossing.com TEST "This is a test message with an attachment." ${0}
-#read -q ok\?"Press a key to continue: "
+echo "zsh_library_version: \c"
+x=$(zsh_library_version)
+[[ -n "${x}" ]] || echo "Missing info!"
+[[ "${x}" =~ [[:digit:]]{1,2}\.[[:digit:]]{1,2}\.[[:digit:]]{1,2}\.[[:digit:]]{1,2} ]] &&
+  echo "${x}" || echo "Improper version string!"
+read -q ok\?"Press a key to continue: "
+unset x
 
 echo "doSQL select count(*) from CART: \c"
 x=$(doSQL "select count(*) from CART")
@@ -19,49 +22,60 @@ else
   echo "${x}"
 fi
 read -q ok\?"Press a key to continue: "
+unset x
 
 echo "rdDatabaseVersion: \c"
 x=$(rdDatabaseVersion)
 read -q ok\?"Database version is '${x}'. Press a key to continue: "
+unset x
 
 echo "okDatabaseStructure: expect VALID structure\c" && read -q ok\?"Press a key to continue: "
 x=$(okDatabaseStructure CART:number,CUTS:cart_number+cut_name+length)
 read -q ok\?"database structure is '${x}'. Press a key to continue: "
+unset x
 
 echo "okDatabaseStructure: expect INVALID structure\c" && read -q ok\?"Press a key to continue: "
 x=$(okDatabaseStructure CART:name+group_name+title,CUTS:number+cut_name+duration)
 read -q ok\?"database structure is '${x}'. Press a key to continue: "
+unset x
 
 echo "getMyIPAddresses: \c"
 # shellcheck disable=SC2207
 x=( $(getMyIPAddresses) )
 read -q ok\?"My IP address is '${x}'. Press a key to continue: "
+unset x
 
 echo "rdGetStationName: \c"
 x=$(rdGetStationName)
 read -q ok\?"Station name is '${x}'. Press a key to continue: "
+unset x
 
 echo "rdGetWebServer: \c"
 x=$(rdGetWebServer)
 read -q ok\?"Web Server is '${x}'. Press a key to continue: "
+unset x
 
 # List Services requires no curl argument.
 echo "rdWebInvoke '21' (RDXPORT_COMMAND_LISTSERVICES): \c"
 x="$(rdWebInvoke 1 21)"
 echo "${x}"
 read -q ok\?"Press a key to continue: "
+unset x
 
 echo "rdListsGroups: \c"
 x="$(rdListGroups)"
 echo "${x}"
 read -q ok\?"Press a key to continue: "
+unset x
 
 echo "rdListAllCarts ${group:-Music} 1 (with line count): \c"
 x="$(rdListAllCarts ${group:-Music} 1)"
 echo "${x}" | wc -l
 read -q ok\?"Press a key to continue: "
+unset x
 
 echo "rdListCart 1002: \c" && read -q ok\?"Press a key to continue: "
+setopt xtrace
 # without cuts, not verbose
 x="$(rdListCart 1002)"
 # without cuts, not verbose, explicit
@@ -72,42 +86,54 @@ x="$(rdListCart 1002 1 0)"
 x="$(rdListCart 1002 1 1)"
 # without cuts, verbose
 x="$(rdListCart 1002 0 1)"
+setopt noxtrace
 read -q ok\?"Press a key to continue: "
+unset x
 
 echo "rdListCuts 1002 (with line count): \c" && read -q ok\?"Press a key to continue: "
 x="$(rdListCuts 1002 1)"
 echo "${x}" | wc -l
 read -q ok\?"Press a key to continue: "
+unset x
 
 echo "rdCartNumberFromTitle 'Drop this CART': \c" && read -q ok\?"Press a key to continue: "
 x=$(rdCartNumberFromTitle "Drop this CART" 1)
+unset x
 # Case sensitivity?
 echo "rdCartNumberFromTitle 'drop this cart': \c" && read -q ok\?"Press a key to continue: "
 x="$(rdCartNumberFromTitle "drop this cart" 1)"
 read -q ok\?"Press a key to continue: "
+unset x
 
 echo "rdCartTitleFromPartial 'drop this': \c" && read -q ok\?"Press a key to continue: "
 x="$(rdCartTitleFromPartial "drop this" 1)"
 read -q ok\?"Press a key to continue: "
+unset x
 
 echo "rdCartTitleFromNumber 999901: \c" && read -q ok\?"Press a key to continue: "
 x="$(rdCartTitleFromNumber 999901 1)"
 read -q ok\?"Press a key to continue: "
+unset x
 
 echo "rdCartGroupFromNumber 999901: \c" && read -q ok\?"Press a key to continue: "
 x=$(rdCartGroupFromNumber 999901 1)
 read -q ok\?"Press a key to continue: "
+unset x
 
 echo "rdMaxCartNumberForGroup ${group:-Music}: \c" && read -q ok\?"Press a key to continue: "
 x=$(rdMaxCartNumberForGroup "${group:-Music}" 1)
 read -q ok\?"Max Cart Number for Group '${group:-Music}' is '${x}'. Press a key to continue: "
+unset x
 
 echo "rdGetNextCartNumber ${group:-Music}: \c" && read -q ok\?"Press a key to continue: "
 x=$(rdGetNextCartNumber "${group:-Music}" 1)
 read -q ok\?"Next Cart Number for Group '${group:-Music}' is '${x}'. Press a key to continue: "
+unset x
 
 echo "rdDropboxStatus test 1 1: \c" && read -q ok\?"Press a key to continue: "
+setopt xtrace
 rdDropboxStatus test 1 1
+setopt noxtrace
 read -q ok\?"Press a key to continue: "
 
 # test with a known good prefix
@@ -119,37 +145,46 @@ echo "rdGetDropboxIDFromPath test /var/tmp: \c" &&
   read -q ok\?"Press a key to continue: "
 x="$(rdGetDropboxIDFromPath test /var/tmp 1 1)"
 read -q ok\?"Press a key to continue: "
+unset x
 
 # reset a dropbox
 echo "rdResetDropbox test ${dropbox_id} 1 1" && read -q ok\?"Press a key to continue: "
+setopt xtrace
 rdResetDropbox test "${dropbox_id}" 1 1 || echo "rdResetDropbox unsuccessful."
+setopn noxtrace
 read -q ok\?"Press a key to continue: "
+unset dropbox_id
 
 echo "logit test 1 'This is an interactive logit test.': \c" && read -q ok\?"Press a key to continue: "
 x=$(logit test 1 "This is an interactive logit test.")
 echo "logit test 0 'This is a non-interactive logit test.': \c" && read -q ok\?"Press a key to continue: "
 x=$(logit test 0 "This is a non-interactive logit test.")
 read -q ok\?"Press a key to continue: "
+unset x
 
 echo "rdCreateEmptyCart ${testgroup:-TEST} 'Drop this CART Too': \c" && read -q ok\?"Press a key to continue: "
 x=$(rdCreateEmptyCart "${testgroup:-TEST}" "Drop this CART Too" 1)
 echo "Created Empty Cart '${x}' in Group '${testgroup:-TEST}'." && read -q ok\?"Press a key to continue: "
-cartNumberToDrop=$(rdCartNumberFromTitle "drop this cart too" 0)
+cart_number_to_drop=$(rdCartNumberFromTitle "drop this cart too" 0)
+unset x
 
 # THIS IS DESTRUCTIVE!
 echo "rdDropCut 999007 1 1: \c" && read -q ok\?"THIS IS DESTRUCTIVE: Press a key to continue: "
 rdDropCut  999007 1 1
 read -q ok\?"Press a key to continue: "
 # THIS IS DESTRUCTIVE!
-echo "rdDropCart ${cartNumberToDrop} 1: \c" && read -q ok\?"THIS IS DESTRUCTIVE: Press a key to continue: "
-rdDropCart "${cartNumberToDrop}" 1
+echo "rdDropCart ${cart_number_to_drop} 1: \c" && read -q ok\?"THIS IS DESTRUCTIVE: Press a key to continue: "
+rdDropCart "${cart_number_to_drop}" 1
+unset cart_number_to_drop
 
 echo "sendNotification() without attachment. \c" && read -q ok\?"Press a key to continue: "
 x=$(sendNotification test dklann@grunch.org TEST-MESSAGE "This is a test message")
 read -q ok\?"Did you get an email at dklann@grunch.org? Press a key to continue: "
+unset x
 echo "sendNotification() with attachment. \c" && read -q ok\?"Press a key to continue: "
 x=$(sendNotification test dklann@grunch.org TEST-MESSAGE-ATTACH "This is a test message" /etc/issue.net)
 read -q ok\?"Did you get an email (with attachment) at dklann@grunch.org? Press a key to continue: "
+unset x
 
 exit
 
